version: '3.7'

x-constants:
  REDIS_PASSWORD: &c-redis-password dummy_test_password_123

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_PASSWORD: *c-redis-password
    ports:
      - "6370:6379"

  s3-storage:
    image: zenko/cloudserver
    command: yarn run mem_backend
    ports:
      - "50000:8000"
    volumes:
      - ../../../s3config.json:/usr/src/app/config.json
