replicaCount: ENC[AES256_GCM,data:Iw==,iv:5ZN+MaVc/YCm4fPqnXEoRZqNUkcsgDDsMCmpApZKTRs=,tag:wa8OLmaFjL4M9X/kbNK8HQ==,type:int]
image:
    tag: ENC[AES256_GCM,data:+BV146XH,iv:dE44uex4j6gCB8Z5hb+rlcTzW9zoB+1fftgR9jcl/AA=,tag:qozyoJHISQ+6To/Coc4pZA==,type:str]
    repository: ENC[AES256_GCM,data:hbbUppQbkknZ/z23kegQwoY3UelyoBzmLPN2or/rOsVcpjn0MAPn,iv:hXYmkof32tHI35DolD8ldgsc037uumTOZgkmF8QpJDU=,tag:ZoyMYbDXB2eZ7nL8Pnszcw==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:m7lIHw==,iv:e2PGYOWqj9FCZ3bFXK4TyYZRS1AHPbWQU0Svo6o4wNA=,tag:UZ1YIBrrtUzmVS4d8W0yrA==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:cM8pZ2WCqzfYUztI4KDi5WuEdPA=,iv:loD4Q0hZzXpUvkSHeh41dLVvVxYtM9eVrtVyuELC6fI=,tag:iouIQpnNBLtSyeec7qlWSQ==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:akzZ7TjC4DPBt+b9,iv:9c9QZDX3xrS2Wt7PjLgHW+1g1qLwGLispAwkx2Ay9Vc=,tag:tIvFnBQOoQDTJ6M3hYfY+Q==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:0t1kpDNkpDcO3Xvl,iv:CaVFukHoA84VGgwuMVHGjHb9XVDzfh2FVrR9sR2Dme0=,tag:4eXTrdvuFFSTUqakAmslUA==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:eQ6MuOcmC46Eg09p+epdL68BC94=,iv:N5OE54CgADuYkpX3rrWTgia3AstJ/kvR7SFBShlmNck=,tag:6mN36R0+yStal1Wglz2exw==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:9kp/LFAG3MteVQXjVBcBqjA5coUZlrKfkSwnges=,iv:OxHPbBPfoeuOVHIvOtN9Vk5EuZiNeWVaPLLYX5UdyiQ=,tag:LiMu5LovTarCjBEEO/Enng==,type:str]
          paths:
            - ENC[AES256_GCM,data:oRRC9qSM9C5v0NTgRPKjKd139omIEiv6Ga9jTQQj,iv:BOWcVOIv+rWyHR3FtL80ZuTBJZlkzVbexVqfepDe3Jk=,tag:rN4zJJLVWnvBmx50lTYL7A==,type:comment]
            - path: ENC[AES256_GCM,data:MEeiRg==,iv:tCuh8AkPc493GtEfdlG5wweNKqbJIv2E7/370WAryfI=,tag:sfY7nrg4jWukbSJMuBEBDA==,type:str]
              pathType: ENC[AES256_GCM,data:TfTndDzmwfkXf9025VY+tm3bGBFK3Q==,iv:817KInSKbv69KLqJqrkHluKJrihFvcKWa6JkZQx8IFA=,tag:9v+cUL0qiYvRayok92xB7w==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:nHdQgC7YQYwZF17jf8itnG0zS06C2F/hg+/FXAc=,iv:l8v61/r1laIzgvsoyPiBWwES5cqtYu1pKAj+ZWwwuuQ=,tag:UeKwqSCh+/KTvx/YMhgujw==,type:str]
          secretName: ENC[AES256_GCM,data:65WoY+UuLFr/KvfNlOblnwZ018ZqBs83zW+qBFk2ah1p0ayCZOUX,iv:4tK72kvoQcGTXydezqeNAY2OO3ACj2V4JUYSGEL7yR4=,tag:/a3+uZMS1M2Vsr8HoRRAAQ==,type:str]
service:
    type: ENC[AES256_GCM,data:1fhwxGELlSQ=,iv:DgFucRw043+wPYPB/8O2Ianp0SkXIQZddnK2Uur1RhU=,tag:Zd1plWucOkboz/CFYOEwwA==,type:str]
    nodePort: ENC[AES256_GCM,data:evRziBU=,iv:VVFP5OKCVo7ZVZOoyad0ByxlmcPyz7wPcwEiJHMh0jE=,tag:yP3ew0C34S78Hib9DrKgHg==,type:int]
env:
    - name: ENC[AES256_GCM,data:nzhGHK6CkEc=,iv:/wJzhwpM4hn2FHX4r5iz+CexxOs5foCUdUg9vgjWTn4=,tag:JVD7q2KIkWHfe9h5BDaDjA==,type:str]
      value: ENC[AES256_GCM,data:D3Enxy9SRy0=,iv:qKNitTdcX3CMq6yD/gerES8xQh34QlqXQw+hL1mqq4g=,tag:1TmW60YJGm4tw8DoWXd7hg==,type:str]
    - name: ENC[AES256_GCM,data:73wj9EDNZXPHXR0=,iv:SDqgI6jLFs9QkregrlvImn0MvKQ4BbjyDaqCI9f+oSU=,tag:OK39x8H/ToNujmvr7iT2CA==,type:str]
      value: ENC[AES256_GCM,data:H0XV3uW4,iv:+hcsr6yOKPs5kmkGAxPFvUA8SmVlzrhU0DYB0oQ1XN8=,tag:p2GbCVFVKhJCx0gkDUl28Q==,type:str]
    - name: ENC[AES256_GCM,data:zVaOltIekdYOk7LqKu+f,iv:BQTHqHnsr1w8/K+W2IvNMgOA6kiu6mW0hTUl83WmJKo=,tag:pyoVV38Ur17T4qKWwOTi2Q==,type:str]
      value: ENC[AES256_GCM,data:dUC2SdgCl7ITID59hp+fIk2jfAftSpYoJaaxmv81bDyYLeFvnj34a3C6eiTz,iv:zWaBnj50VFFaxgliwIolB68Gv8zX00fKaeCyKCRoyAE=,tag:DTHFFwRsRJvBB1jaffc2DA==,type:str]
    - name: ENC[AES256_GCM,data:cfF2lL8p3LBgjIKcgrIU,iv:PG7a6STQfC1sfJo9kYSBwUgNQZxYwuuyJZJPnbwL964=,tag:kniL38sJg4eFmv/5rzTjeQ==,type:str]
      value: ENC[AES256_GCM,data:ZHFPiw==,iv:KFWjcc/6rtPWCubpGI7PhsaT0S2919tQLa2ziQi0eLw=,tag:nWyw6+P7QfZk++VqL73bZQ==,type:str]
    - name: ENC[AES256_GCM,data:MX+R5lB4cnu59C2NBA==,iv:Gp1XajULz6SpciQG9UHRLXK9PqtBXy8haa8agcS+XGs=,tag:w5en1ZrEo/tCF9galqws4A==,type:str]
      value: ENC[AES256_GCM,data:NQ==,iv:y/g4U0wrBIksrv+KREAGbdWqU7VXVDxKFY9jj/+zMmY=,tag:9Mg3Bs3KbNOzq0ipINE+ug==,type:str]
    - name: ENC[AES256_GCM,data:b7Pw0WIjkoXsMbSwlAOe9Q3DDA==,iv:o3wrSnnFSQtP37ZZsrN8cPiKI7ZrW35dbESgZ/B+zMw=,tag:I9WRzQcbHl5/QbijvcV5qw==,type:str]
      value: ENC[AES256_GCM,data:riHinEqw3Gthbhwy6z8i,iv:oVVWuOh/yVTcPeUTjMXrxxVjmJpNVtDu9LXklOZiYAU=,tag:XzP2R0zE1mFSrQ4WO4goIA==,type:str]
    - name: ENC[AES256_GCM,data:8lBjYEsKeRPn929abec=,iv:6/AuFmSYGF5l7Jx2bGx2El5ZZH1kRwwRkXoKBwYzXUo=,tag:dI+WYs/9gYNJhHjgYsz6AQ==,type:str]
      value: ENC[AES256_GCM,data:jQ==,iv:d9Kcpl1silc+wE0CyeqF6C8ZBa7uJbJsmx4avMBaMt0=,tag:ozROvC+faLHEnkMfavvzNw==,type:str]
    - name: ENC[AES256_GCM,data:v7FY73eQmBrFK/IlaRXdPPEebT0=,iv:HIX+mEC/CBNnlWq7K9rmkX+/q7rV7JHQjFS/4bkq9Z4=,tag:uqMikkd32PPG5Vl3alBweQ==,type:str]
      value: ENC[AES256_GCM,data:w0WCs37IXDRI4oxDlbz6kUUZMt6zNzvFK9MhldzEBA==,iv:94OFvs3k9Ub7SjHMl8NWIGgWEcw8Tzud3BopT3vUEUM=,tag:dO+2Pta8XWX0ic5hqZjlig==,type:str]
    - name: ENC[AES256_GCM,data:Kk6Mw3zv2EBTBIAGmdIzwA==,iv:1frDRQQiOBzNibuwgdvTBKbw4U9bdu4652QITCRU6YY=,tag:Q7DlZ5upqnv+dZTaIUzX+w==,type:str]
      value: ENC[AES256_GCM,data:2XuIVteGlrriBkRPgbNFOhOXJsM/s4/gS2UYLYejZBMte/w0sl3KrcWQI3GC,iv:aboHOkFxYeaOX86FZhh3apVxRJ/2xhViluJ4UAf7Jj0=,tag:/sGYvOz2cxPuOZrLzSocYQ==,type:str]
    - name: ENC[AES256_GCM,data:TVq/PRaOUSUkB58C8fZ3Dg==,iv:x//GqBzOS/sdLZ7uCgUXGnM+tQzoJpOS4xufMu3EkYE=,tag:plFUK5Nmbvx05Yg9NH7jMw==,type:str]
      value: ENC[AES256_GCM,data:FQ5WGQ==,iv:kTcpsBXpTPYMGmIU1PTBT1qml67vb/42R7yqXj5oATs=,tag:++ShBCTmzU88b1iE4E6zUw==,type:str]
    - name: ENC[AES256_GCM,data:QCiyQr+tuXhUWF3x3jM=,iv:sVr+MLQNEO7qwbn50u6MrelpukUxkjYg/DVDeWYrkfA=,tag:Ems7vZjW94/XMZy3H+uoEg==,type:str]
      value: ENC[AES256_GCM,data:Vw==,iv:cyUwxTYmjLj8IgeRLGdaCEA7B3cqoIFwCz4H4ULSwLo=,tag:/GarDdgNJveIrUxhsFhMzQ==,type:str]
    - name: ENC[AES256_GCM,data:NpaCZTCeEPJIe0tznSBAOGlMpvk=,iv:/boGQ4uPTu3oW+bVl7AOmIsEFPi4Quxid/OGpPhvokQ=,tag:0giyF9aD4vY/UNvLeEFbpg==,type:str]
      value: ENC[AES256_GCM,data:WX4nd6iPAI71WVX3gHVW,iv:OOKwUQ06wytg2bKM+DZ2hEnXX1lIn2woWebBF0n58+s=,tag:MQkdwXF/7itr/Ymf82jDzQ==,type:str]
    - name: ENC[AES256_GCM,data:XYefrLtdsCD59NkjVof9,iv:YWJkZlbWwXlIa6M0R3chJ8Huch8bQfY7sDrtQ++P6wM=,tag:gcCeV5n/RXERGomIR24Hag==,type:str]
      value: ENC[AES256_GCM,data:Tw==,iv:o+++heGQO1dF025Digt/U7YzDsvDDGQNEuvFxp7re8Q=,tag:AP2Dtl7abEfhKVNtd2fscQ==,type:str]
    - name: ENC[AES256_GCM,data:cTfU8hUl1S0hS3cfCWmpOF89tw1L,iv:J9bLqvLFcOo2G767m61k9FLk3ZvsS4hE34BGwWCy+ds=,tag:g2XGUBzVBiL0pnwVvrVing==,type:str]
      value: ENC[AES256_GCM,data:AecVhtagQWSrccpolIbU1xXiQ3BhaDbQscxkXFo03Q==,iv:nQhtK56cv8nu3TUY1rB13Tuuq78auN6vevijKHK10v8=,tag:LT/h0kElh5VwmUIwsh+d3g==,type:str]
    - name: ENC[AES256_GCM,data:0mzjQNstNck=,iv:niP3u1gZS6n9SefFNJG0S7au2Vjpz5sbDIWJyWSb8zs=,tag:hV9d4aBklSaGKeggEQTHKA==,type:str]
      value: ENC[AES256_GCM,data:cegnOJmspJiaM9lJ60rZuIg7IyPjRtUdIhfSBUgtnQ==,iv:5ZaWFV9IIeAoI6YL9M6dAhSynjCSrjyCjXCRHO9GgDw=,tag:7DNBggQBTNP/bDvsaBZ0Hw==,type:str]
    - name: ENC[AES256_GCM,data:9xzPuDDeKm6GCA==,iv:5W06QT/34mnDK2MUnmXMgRjfUNBrNE4b8azzeRrQmwE=,tag:IXN3cSeZLzia8GudQr4bUQ==,type:str]
      value: ENC[AES256_GCM,data:vB9dZUza5Q==,iv:tD8qkXAL7mTNhPgRmQFqdXXFRdNrOswGPkCGSsuilKA=,tag:Fj6CLWrgmDn4xx4105r0OA==,type:str]
    - name: ENC[AES256_GCM,data:ezlKaw7lRUdwRD/69U5tTCo=,iv:lxZAWltBAJ2DgdSZEOwNfsFu9DVSkXInqf6L/HOAn1U=,tag:F44QoPLoTNSe+oUVwyDWVw==,type:str]
      value: ENC[AES256_GCM,data:nXNb+YWd/9fhCbMqdZsBn+1xCT997c70gw==,iv:mK/Z4OAADeSxijsfcDicDCqybiOc/Tj4ODhcHIbmO+Q=,tag:UdfPFev480oUOVDxCAgWtA==,type:str]
    - name: ENC[AES256_GCM,data:4vVXwPHCU96wxSOyljw=,iv:l+NdhX1tRKg5gh5QqUkK4rJpFGwGQXltc7mUTzdplFE=,tag:UTV2OkXUS+80di9zCCQA4w==,type:str]
      value: ENC[AES256_GCM,data:ertlrtExKuKG8ln/XlNF2/oRgYhJNEZjMuh2kxkJOsHKXj6oxbQ9oA==,iv:aPv2FX9zhTj1PsYbVyBrV11fizKgcc+bslxQedx9m/Q=,tag:c0wEyg6hBruAraXS0WxIKA==,type:str]
    - name: ENC[AES256_GCM,data:6An7H8+/OzcVUKohBeI=,iv:dfsdCuTmgedUSmj0y4rEKcB/ZZ0vVkL3cqK+QbFnvsc=,tag:9Ncm42I75aXRF+Qj2JCJ6g==,type:str]
      value: ENC[AES256_GCM,data:8Fp27XqK+TNKqTUqpuzf7n25yTiHrnXwMrFauzRU2scpdn5tkg==,iv:886tEnDNiLIiDBAVnzLX4/P6JdMC7OQULsKQer1dPR4=,tag:dFzChQQz9rql2Xbbb3RJvg==,type:str]
    - name: ENC[AES256_GCM,data:qW5+BYlAT+YJi8LQV/QJ,iv:Nuxf5GhekhVxkbxRaGCyRAyJYKKEByGjIr+HzjSp5s0=,tag:7F1IzYiVu99nHP411OC1Mw==,type:str]
      value: ENC[AES256_GCM,data:krE1wA==,iv:YJzCX/zzlYxBmYSfvw/PhVb1SsSNAU1AeLIr3DktV+A=,tag:O+EVnkAYSxOTiHyNTXhotQ==,type:str]
    - name: ENC[AES256_GCM,data:jhyniP5BDp7ru/uiC3L9BQl2xg==,iv:k7NWIMJWQsyys9GC+eCaxMEDw00DX7lPxh0/hGNxIZ0=,tag:tN5BSVuKgEkgtLso3skc1A==,type:str]
      value: ENC[AES256_GCM,data:o5nJLhuFX6DxXhfX,iv:q/JzfNSKRqbXTQTJK5pb3c8gSERBnivYqxbrnYzQkDU=,tag:CsJ9v9jDPqa8rUkqfW3Zfw==,type:str]
    - name: ENC[AES256_GCM,data:j9MGyOM+USMUb0mgQZ3Q5nHm6g4BUA7C9L43,iv:TGOj3cQ9QW6wz9aJ91F3KCIIl0Z/2QwHuUEbk2eKBJs=,tag:/Vs7oDOpCS5TwVdkN4o/KA==,type:str]
      value: ENC[AES256_GCM,data:SWOB9lWGOV7Pu+T5yGGrg0UNrnpptntbNE/K16Pq94Q=,iv:caaxM/vOhOxgvaYfGDe5/jlwdy0mwbCYfnpK5q/FP00=,tag:8vMZsi8Fz/JulTRH5M65UQ==,type:str]
    - name: ENC[AES256_GCM,data:tgZwSeZsn+xsWsU5bomA1zjFvfGRc6pWx1Xi,iv:fZovCoGQosp/chPU7skGjhdgjHgJqTGBPlOXkNtSI5E=,tag:eS3bAGkXcAkjtAAIXYBEBw==,type:str]
      value: ""
    - name: ENC[AES256_GCM,data:xfXhHsvFuYsCHbHB8ttHhfklB3YhOwOo,iv:ZyY0xNFjnuyy7ymNa4gVWZzEipHRn+1vWuf9H2QXlX0=,tag:dTSp4I0AqqXdgudyEj8s/A==,type:str]
      value: ENC[AES256_GCM,data:5n5GYPY=,iv:ZvDSdiDo4NNxOxoayllgyCiPMaLURWb/vpsnqWysRI4=,tag:Jymae8PmobIGfkj8SDKk5w==,type:str]
    - name: ENC[AES256_GCM,data:UXzhpwabOYia8lc5F7wQMOxfG3DuKSGl,iv:45NsZ1f93VY728EOaUp5Q3zK0sPtQFInMtbt59nD6bo=,tag:582cyDtBkn6p9s0SUBvs4Q==,type:str]
      value: ENC[AES256_GCM,data:/keXqei43dnaPH33,iv:LWBk2iXdVPDVaEQM0JiRH4m/A+L6SF5fu5c51g0hgyk=,tag:b16HgzQjYlJRnc9Y9Ra4hQ==,type:str]
    - name: ENC[AES256_GCM,data:jZqrrdepHBJwM27o3Eeu5a5IJw==,iv:1sWx2ROUslbB9TvfBmjdslJsoEUkWIUISf6lwpB3AcQ=,tag:nMhr9bxG40QPkKfKwYaBIQ==,type:str]
      value: ENC[AES256_GCM,data:nxdedtQ10gqaAiWaSYz8L7w3S4MnI77CZMxxenyn+8eYwaGV2Q==,iv:4DSz/TAq2sP9SwnpfCwtpca+0gRrD9/y27F0P0CHSpM=,tag:kFPwpMOKXRVPbCbs5HvBFQ==,type:str]
    - name: ENC[AES256_GCM,data:eJV2SH/lVLYpMc9DUP4gw+5RRw==,iv:hDnYgSYSseYA58G9VOX0NDh/kvbez/n1bLai1ecWRMM=,tag:eIRqbZflIud68iDo7wBpvA==,type:str]
      value: ENC[AES256_GCM,data:reoR3rgEsLqB0VrgnmUnAhrh2iTFAz9l9MfunFz5POpJOgBccmh7cTttGX9osa3cIzdv0ZrLUSFU,iv:0Bgi21ViK/hLgBgosF1osVSNPmmNmbNesXgqA8NzYSM=,tag:FwRcGNpz6/RjMcsNcFPm8w==,type:str]
    - name: ENC[AES256_GCM,data:vd3eO3roNp1n+sjWsY3677vpqg==,iv:c23q0HQavtVfUlThveivAD7q9JLU08NU2peifNjcO1Y=,tag:6ndJTC8LvXytlPWiLl2d6g==,type:str]
      value: ENC[AES256_GCM,data:f0Dqf5PvBPn7f6R/HyblMmXKv6LruOuLAKSFWmblCuBf,iv:JiK7CMflqZVfpvI2k+KBLVhWQgXGWarAnZIw3wTaZg8=,tag:WjiGk/krtmX7tW9VWwR1cQ==,type:str]
    - name: ENC[AES256_GCM,data:ruq36n3zW5MLYJb5CRN74XL0gGG56lE=,iv:RhvrWOMNnuNKIiuHEmeZJ8dQVHMtDIMqYkReeTXYYs4=,tag:z7Z5773kTaPD1XYba5CKtA==,type:str]
      value: ENC[AES256_GCM,data:OA==,iv:DELUpBjnKTv/VrXqrp+yiTJRO3PoZoRkJsBACjOaUi8=,tag:Q/jlR0i0n/W80pYQOwqyxQ==,type:str]
    - name: ENC[AES256_GCM,data:Vn1Uqg7vHCjd/fUbxIL6ozCdTDc=,iv:NXNjDpFX08h3Ayo4pzHa39E7pGUDjwEIadLLbhAFJ4s=,tag:KPtBydLIvARZx9/xI6atRA==,type:str]
      value: ENC[AES256_GCM,data:crejfkfePI9H3ysO,iv:Fg2QaSf9khf7iAuXPqpVKpa3IXXLbPapIG4hmNd+jzo=,tag:1QaW0l5DjyxK9X82WLLzwA==,type:str]
    - name: ENC[AES256_GCM,data:kF8iGaPaRYk=,iv:US9ipi3LyCCzE1h8pP5QOsgOtlGXk2/KtphS80PPBIg=,tag:NkgScmCYvUjxVu8XQV/K4A==,type:str]
      value: ENC[AES256_GCM,data:dcXO1IrU5KLEak3TswgRNgbq5PGZKKz8Q3gjM7B4/t94HrE4Lhn8bog=,iv:oC3hgTQ1n9JSMkHMGkHniuiJr/BRQ8Ik9G+mv+tnmWU=,tag:trXkzgkWPUN6wxUa4HAzwQ==,type:str]
    - name: ENC[AES256_GCM,data:zUph5x+5xrY=,iv:h8x+yrBF7GjgZGhvAFNoD50QqMJtRngKXtv+2Nm60s0=,tag:AJTla3cM1KxKVt7ybNLxMQ==,type:str]
      value: ENC[AES256_GCM,data:GWeP2A==,iv:IdCXIuI0U5bP42BQRxRO0KpXMdSslemRBv90N0tU6pg=,tag:WqiezcwwaRcjnaiaxrRNLg==,type:str]
    - name: ENC[AES256_GCM,data:ex8xqst6SSMAKLGN,iv:LZ8l6jwt/8APEEJAnu2MD1nFMLkK6VoPFK9u9gM+Rqk=,tag:O4criAymnZVBQH0Ml46S+w==,type:str]
      value: ENC[AES256_GCM,data:R/UvE/iZ29qQnm1L,iv:Gn7IIuR7JLQzdvrWmO6/0oqJHYz8Wffw/+JiWr8vnGs=,tag:2M3Jetqc/EDt8ROog+UqZg==,type:str]
    - name: ENC[AES256_GCM,data:3tEetVZ1PMDt8jyA,iv:xcCKqT+g7cwLqAHjyoyR9uPMEGKAMvYM0U6UgmUprXQ=,tag:dzZljo9V0rCWaCYn5/qhXw==,type:str]
      value: ENC[AES256_GCM,data:Qc4iTgu3y4I28D5W,iv:EleEtKsDBtrkMpEAsYtSG0PUVz2cCjZxpdBNbCNsgVM=,tag:DA1rqC9tv9DybMwOESCuyg==,type:str]
    - name: ENC[AES256_GCM,data://QwKnevGM2ZdkQ=,iv:Qu4P4fMBQQ3TAPJjO8CuTyZ9MVGR1W7keiWe5AeUybs=,tag:PWtzv4K4MN9Trbzcspo/0g==,type:str]
      value: ENC[AES256_GCM,data:3puuh70z,iv:aXFHl5DE0wCwRyfxk5MW3ST9JDa1lfvcfg6hQCPCjlk=,tag:dwytTDsK4RlhkHe6enXjWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdEsyWVRZUmYvTHJFSVdF
            Ylc1aHFCVG1na0dXb1o0TGUwN2MzWFRQUVFzCnVPS0hyTVhLRnIvQVBTTHlYZ21S
            M1NCZGZTdjRIRnNSNWtUS3cweUVsK1EKLS0tIFZjaWREUC9MR0IrTlNTd3liQmsv
            ZUFROWRGUEV1MUZZMkdpWUtZMXBMQnMKrWaYofv5cSg/1cRvZY9IsJRbspJc4K4P
            uvR81DzmiQ/ISRtij4Etn1vY3qoCkN9qC4fpxN0Cc41jA2fnhPnB1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T19:43:20Z"
    mac: ENC[AES256_GCM,data:hunbDAiaPHa+JhS+yK32nbBjxaNCNoOCBln72ccdWyhCgONYC9UYWGhYypJjAxtiHhf1UdMEyxB1/OLK+qRDQFFPie+Aw/MUdiSEgSdxwWToJXFR+hhRpJkujVEMeU1f/OpsNC5db+uzybcJS8Bav6QnvdKtkWqXBovMWawoLS0=,iv:tTHDbrVNJRs7jeq1yFEll66SOdIH2LkczE0XbwpJTOY=,tag:eT2wgu02N87wtys0kcG41g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
