image:
    tag: ENC[AES256_GCM,data:1sZ3xWYL,iv:wb41E4a3G1gmMvTT+QCs8KxWTeoDZXeYv5OenVh+42U=,tag:tsONlzr3aIAnIiZSLtYsQw==,type:str]
    repository: ENC[AES256_GCM,data:Wyd5N+f3NY5A7x/ZYJX1renyrFeutCRlO0L/FTrJM4Z1q7YgRaEO,iv:lqolJshAOXGhpQGVuWzSgbP1xD2HPgETvFQJn4ZEZ+g=,tag:heWWyNC9dGNJnS/UODxxAA==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:cVMNOw==,iv:whg8bD1m9XcVQSlm4PJNdU6Z7hnlGV1I5lTCWY9x+Ts=,tag:+UdFrdfHbq/Vbu+osrhT4Q==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:bqVQcINFU62vVK+VjqRK8d4lYGo=,iv:SgpLN7T+hDGMq7m2igzpKv4jVLPSLI1BE0+Mm/+htq0=,tag:zXbZLHrtpZvfAdwEgoD5Ug==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:7ckX8TjC2EVuoB55,iv:6BSAIxfx+ITPbqcklsCEbNNM5UknD/qfXjENKSiJXO8=,tag:hdiKJ+V2NVaOk3TwuTsPxw==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:VBxAdtCsulTwOVBM,iv:b7giX//7LROSrDoyAZxcUgFkm8Ye6vJWmEX6NX5u1B0=,tag:fk6kqFLbPDTdkxPmDzlbeA==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:m6Hp7V6GU4pDjEcgAAB3p/HH3ow=,iv:jtOX0Ekth+evcP9qfd/NcTv88N6+aTU+ScHZAi2GSWI=,tag:vH4+kL/kc4a5VjtJJ8bmtw==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:/wrYk/llA+2f+yh6VHej8HDvT1SOphiEUgjoY5Y=,iv:DIlndncck2v3W111v8vfXXD9zq4UymgMDLVaDQEIwqY=,tag:Q5kF2SzIoLxvrku711RdaA==,type:str]
          paths:
            - ENC[AES256_GCM,data:h+3j4VRI6y/gfN48CKWhltVLQzLvKzVKgIbNPyzZ,iv:ekcDGALSWZNabWPwtKsc5CQIoCoIVSLUQ3nGnwgXp94=,tag:EHPt88O1yEkGC4RgcS0ACQ==,type:comment]
            - path: ENC[AES256_GCM,data:Li8neA==,iv:Tx2P9xcHGssY4KT3c8KEPkGBLlXmCG0QGurl1REJki8=,tag:iCq9Dx6yT5pLtQRnXhqZzw==,type:str]
              pathType: ENC[AES256_GCM,data:RIzUKXWkAP3WR1RcR2GMnFD0h5Udxw==,iv:tSALue0oIrdOWAZSu5oXjbwaxGH7zLI0v8TzFIygE5M=,tag:BBQEw9fmx6nhoK3H61mlfA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:vgo5EtA8pSDFIdBFJT/cszOlD9GgaprB+YRX4Go=,iv:sZcbnWDFiW+nIz05sbjpJHEOxq01EY2Xzznzj5GnMGY=,tag:59pNEaAnF2hnGluU38VVtQ==,type:str]
          secretName: ENC[AES256_GCM,data:XL/gEU9hGHvSeaqnMyf1Rqvp0M+dpmqBsuIPfSHBPJ28LRqJaVi7,iv:ETpk7s3qPxfissP2FrqT8OgQt5bGuYsTG4OVb6s7uyk=,tag:nrzgzrri9YDMxBYhQE1MJA==,type:str]
service:
    type: ENC[AES256_GCM,data:+5vY+kIyQ2Q=,iv:KWckoaITKyLQU5wxI88moJXlNWTGJN0vCZdWAbu811o=,tag:k8q5zzHVaqiSEnR48IV/2w==,type:str]
    nodePort: ENC[AES256_GCM,data:oqOKzU8=,iv:sJY2+/caBGSCT6YuVhOF/4q1jRCkQZGDBXmqHXYztkA=,tag:0WDLoiytenxorfR15QIzaQ==,type:int]
env:
    - name: ENC[AES256_GCM,data:0PtjdEwSJWI=,iv:pp6VmLmPk2XT9H7x4aMpPUqmtQqzwn+ZfCrg2A5z/Ag=,tag:haD3uZvu6v/rX+5Xih803g==,type:str]
      value: ENC[AES256_GCM,data:AuReHmh1EU0=,iv:WEZEpWWl3huVBh3arUs2K4uWvJz/DFu1IGbhgv3A9B0=,tag:CDWoOHEExKBfkMZyMLYs9A==,type:str]
    - name: ENC[AES256_GCM,data:czAg+7vNoOGbBGc=,iv:clBFvzv12hXaMYRn0QiQh9YA8xDS1rNVlWDLOObjnGs=,tag:qxsXiLNuId9xtjry6Q9LFw==,type:str]
      value: ENC[AES256_GCM,data:zx8aZhdH,iv:ktAA9S5aEyQHyMNK2O6qH5LHDq+j43vfK4/KS8W5PIw=,tag:w17eUx1lQlB+NAhYftxEng==,type:str]
    - name: ENC[AES256_GCM,data:H2ArEAgpwu8p0Zi2zKgX,iv:szuXNERFanWRwZ/0q8WmcL96EHKdKP/MPb/usUfuzwA=,tag:pJ0hcJl2YhZ7HKUpBpgQcQ==,type:str]
      value: ENC[AES256_GCM,data:Enk0sEvm/wu1VnOY/6SAkdGa59azGUKVR+ac+mF8gKr7RRFd24aAr1ZVNuWx,iv:CyweV2L04hvhIxat9SIcwOx1Delvx97qf9D4QQSTY+Y=,tag:gO8w3aiK6Axi3zpTmoNuGQ==,type:str]
    - name: ENC[AES256_GCM,data:bRVtN6s1phBkxL+rqXqj,iv:+Uf0J8lI0AoXFI+UuU1DfJpyLF4mrRlgr1RCukfXjSY=,tag:Wveh+mRvJWE+pO+uW2HqFg==,type:str]
      value: ENC[AES256_GCM,data:aci2sw==,iv:61HtnssCvIJkZj2t8R0LAumjEsH909ewbX2FFveEHEc=,tag:D+IdStl99NvQjHNvzcVhdQ==,type:str]
    - name: ENC[AES256_GCM,data:NBfYJGWsmkwyf/2F/g==,iv:j59r6VWtlWik8spQ+Hhc7XW6etC9BMYo4xyJxU/SzDw=,tag:gPwHOsaTn5FYBBgs3XAgDw==,type:str]
      value: ENC[AES256_GCM,data:Lg==,iv:hP+Sphb6h480tAICKfRBJyw0Pr8ZlGSKwS0kJssRsF0=,tag:pvYw5PzonejDi9ocP1Xy2w==,type:str]
    - name: ENC[AES256_GCM,data:H7+bgq/OR2OPWMrc3+p9uyukzg==,iv:4kbOyaJatD3/yzcvIMu+bE1dkWfpoL3CwallOua5wDY=,tag:9Ao/4KLnHkHiAl/C/tpHSA==,type:str]
      value: ENC[AES256_GCM,data:4dkJLPLQsvkh5f734ZFx,iv:ojmrAEaNhR0lTt4euAuGN/gZDXFSPSXV2Fjc7T2EDME=,tag:37NjF6pbhOE8odg98xuSHA==,type:str]
    - name: ENC[AES256_GCM,data:DR6n2ET/MYDNZDG7fIs=,iv:Jp8jpMXWPcI/GIQIjqhVWC8HV3aRWaXQSwHDFQ7Famk=,tag:yf5P0MLjXy0cxeMJcD/eew==,type:str]
      value: ENC[AES256_GCM,data:Mw==,iv:GxhFl+PUvx46wJ0cG6RC8gGIsq8ti/KSyTHB3PQiUtU=,tag:TSIhiyJykijQ7OaHPpXYZA==,type:str]
    - name: ENC[AES256_GCM,data:Gv3xWUICF0I9tX9Klrq1gXu4eJ4=,iv:0HW4RhmzBD0Y4qoH6Xb962vuNz+zvLdTLWGfQIvyDSk=,tag:Se1xcExk5uSdvmwfSYiTzg==,type:str]
      value: ENC[AES256_GCM,data:Z45RrUxsBdLJ8EVhX/Dn+Lmxex14AG+VToFTNNYL7A==,iv:Vjv1tlLv3wCOGWWDpyjDN0EOx8gXiOFj7W5/crolhgY=,tag:gWOBeV8oTRo3NX+52XnfrA==,type:str]
    - name: ENC[AES256_GCM,data:SmL1xkdjjAetdpTZx7osiw==,iv:hxUvZO54WyyFbMkcXefORwyJf3O+jSTkbcmKlRUVwGk=,tag:hTzN60Jz4nFZ+9qLzXKu1w==,type:str]
      value: ENC[AES256_GCM,data:Deed4cWHXdFQB5pozCx0gCVTrios+to1tyPNuifhDJYcUCS89jO5LwlS6hUE,iv:mP2LEYkfMnJtfvrTMP7kQmUyyq3KqST0/UR0CQppBOg=,tag:Zy+U7wblUkpg5UoTre8I9w==,type:str]
    - name: ENC[AES256_GCM,data:eSykxIdt6Ust0T1/fVaCGg==,iv:4pR6JUoz+3qefhRmFfpVvKBpmYhSPj4z9tUUk3DdLRQ=,tag:NMH+enk9N0JEfPfYLwEZcw==,type:str]
      value: ENC[AES256_GCM,data:8w2HJA==,iv:dlWAvNbifGMwkPyAbRvoUCZ9bkcdI1n3Ije5XUqzIGU=,tag:pFSSAgZNPu90pikj5300WQ==,type:str]
    - name: ENC[AES256_GCM,data:Cxh4xB+TWWM13cGPoV0=,iv:qKA13jz+CsafkfFz8xufAMJP+bM5gceX2jYrFIvklEw=,tag:JdbzUeB89CviPjrxKGSjcA==,type:str]
      value: ENC[AES256_GCM,data:Tg==,iv:ns9wX6E876jXQPGuHFdjekQQnaRbRP/eWYNxrlM3Wjs=,tag:qCL6Ve/VdFmxX1ZRQEuznQ==,type:str]
    - name: ENC[AES256_GCM,data:LsBsdpbakS3MHef7jpoQIXMVRis=,iv:k9+Dc2gDJ1W/oq7UpUYNlRvicofoLmbzppNODTZiINQ=,tag:iNmcPbRYBFm8YLjFihTmsA==,type:str]
      value: ENC[AES256_GCM,data:N8NRdNEvfL/kqdx010o8,iv:kx8D7yMlG8yEGlO8Rcmqo0d0ua1k87xQbFi5nKTzl40=,tag:mqn1759q8mFRVytw0ZTGzg==,type:str]
    - name: ENC[AES256_GCM,data:MPJssLeL2zANYiBT9jU6,iv:aJLYOtVhEdBhsfaFuDyS6VUXl/0eq7rMb7iluREpdPw=,tag:k7Gxi0lxN1pxikHsSQ0k6w==,type:str]
      value: ENC[AES256_GCM,data:wQ==,iv:9Hc5wnp+zUZyNlrx/yJ1StLH6ltJsvWltSosrgmVUhk=,tag:409+vao/+NxWk3uePRhFaQ==,type:str]
    - name: ENC[AES256_GCM,data:d/0wTdX7s/7pBIEEETPF3YhdCp3w,iv:6ftWOb09kH3y7O0qtu41l/zJX2t8eW/sOdcFyIOVkOI=,tag:lctPrO0DEig1WYR16ZvM3w==,type:str]
      value: ENC[AES256_GCM,data:L8NE0pDhfhvCUrj1wAPqX2zkh6eXsq7GB+WQvr3Vbw==,iv:GCJA1vLtd9KcfjXVQopC37Uvj9gq3X/2IlifzW3KNRE=,tag:fGIPqbRUxszQPE2Fk0+7xw==,type:str]
    - name: ENC[AES256_GCM,data:yu7eA5hZI/o=,iv:rnH/MLg6q8iB8dQPPHRYwx38NWM11yBQV7yLqOZaNng=,tag:2YdwXQCTWauDjY5lAk9enQ==,type:str]
      value: ENC[AES256_GCM,data:B3KlYscI56IjF2pBoNL5GOABcL6UVTdXvXXXBIDXng==,iv:l3Jp3qBitIrh8itsUCt8pDBHyTWbqop21B2wscMXepc=,tag:KSh/NSRG/tzDczk6bj4BDQ==,type:str]
    - name: ENC[AES256_GCM,data:wzNVOd757gzBsA==,iv:JwcbfgsntBWIGhobE86eMB4E4Lqdt+eauTwUMnpY0dk=,tag:osK9YWQIYRcJBFzF1YwXiw==,type:str]
      value: ENC[AES256_GCM,data:6iVOOUi8xw==,iv:FXOwntbGbrudnnMAs9ppbzI3w/St19rUK9WFQTkGryA=,tag:rqRbuNYR3iPgehkanWhpNA==,type:str]
    - name: ENC[AES256_GCM,data:9zczVfL+FoVEyHbdHlXU8BY=,iv:IXjeqhXSqyaM36kuOP75cU7WSkBDipMp07xsWXV2gPw=,tag:TLZpkqlqu97buEcfYnPSiA==,type:str]
      value: ENC[AES256_GCM,data:G04L+whlL14bXvuI3mVniYsr5nqDCX5KwA==,iv:js4Y1iCZh7ZkoX0iQMAxCJ+KidPRhk+gWoI5+Hr6kOQ=,tag:yj2sWOFB/oK2X4hAxQuxdg==,type:str]
    - name: ENC[AES256_GCM,data:appEU9FkKTMLKD5YbYY=,iv:3nBhpb+ZOt8HihnElHT/45djAWWzBhI4vMfBQrRw5lQ=,tag:Z3rMcX2/8eX0OQNQWW+e4Q==,type:str]
      value: ENC[AES256_GCM,data:STS5jqtHKpQEk/nGwIQ3D26xB6CrgjBjl0JJvhE7wxOBepSrp2eQRg==,iv:5gCtFPjI9spTKut/tJ+jMtur0shIpL5xg80sLkY2gtE=,tag:2M3WvpmH3xUgO2e/ZwGKzA==,type:str]
    - name: ENC[AES256_GCM,data:67c5gmZbYtq2kc13NQI=,iv:sA2Oe7RRr01uzmw9kFXdIkkLY1WUrux+1+rYTaZ/8HI=,tag:VWI7LcTcM6yIJq8tw5V9EQ==,type:str]
      value: ENC[AES256_GCM,data:XXtgu9UXSyQclAxL3UnQSsJDow4jRzbKGyS9NKH1/6Rc4Qm+XA==,iv:7VRjoFW2sH2ug6+r55oIj9hZMxDLz5hF1kQbMXW8hX8=,tag:T1LynYT35VjL/3ek+OhmQw==,type:str]
    - name: ENC[AES256_GCM,data:iycLVixS03I3VJYQdwAi,iv:a2yXbsxVBilo32TZXEn69uCbZz7+UjuLs8lSDfLRetQ=,tag:tFjN4gQ9pbOhcdjmrdrmvQ==,type:str]
      value: ENC[AES256_GCM,data:SDvawQ==,iv:PlZtH7eml6QyB+PDQ+iOKAHSUOFO+I0oOf2y8elLSjc=,tag:sWmXCCX1XlZtJxxRMXP91g==,type:str]
    - name: ENC[AES256_GCM,data:IrKUL/xLfhZxmeb3LQnBs13yJQ==,iv:0YuEDqpdy2VlhklYJaVTIKQjkDNcQRJjbWLICFLpN5k=,tag:vpc3TAWpRhCTPfiRGSogew==,type:str]
      value: ENC[AES256_GCM,data:5cULRP4sekZcTxCW,iv:Q6M78TnH98Az+DBUvsfA7W+CC2X54DHyixKaF++HKL4=,tag:JQrCUGObCttPGdq3ppWZhw==,type:str]
    - name: ENC[AES256_GCM,data:RDUJ9b+QQzOzO7ZzBbNb5vHAzNvsjt/Kf4La,iv:jwl1jvh0gXwYMOJ+TGOUANVhQr4KKyBCLco9Lww6mbQ=,tag:Vjm0JxSS+0PUzc4afR1hYg==,type:str]
      value: ENC[AES256_GCM,data:4BkslzL2MHm2T9dHCuWWM+fn2vi4v9ogAk3kSa8uUf4=,iv:7wfcKZkmFSBj1QSyggdYiYZcc5QRz3RuXSvM99+1Duw=,tag:tNARxsTceKUjyMIHGLy74g==,type:str]
    - name: ENC[AES256_GCM,data:vJoBhWB+A4IiKq3lp010Sgs8695p8o/yDS4w,iv:ocxZ/GUy+bq2GNz2/WRNA/nFiPkCbiH3crP6IlrznFQ=,tag:pqFsV+ctR7m0IUm01gutsA==,type:str]
      value: ""
    - name: ENC[AES256_GCM,data:eZFQlNygFX7IOUl+cEVYnSYMgv07TVan,iv:DgNg0Kn1dxeMFTTcNV8CiznOk0QO1x9I6GbrAJsjVlw=,tag:vlhXrNUbX+PAzURjk0IiyQ==,type:str]
      value: ENC[AES256_GCM,data:vp7blTU=,iv:JifL2TJHXTuq2yMKLtbOF4D1PapB160E/HCsP4J/Ndo=,tag:IZoX4RvUja7+xiSFqqjK2w==,type:str]
    - name: ENC[AES256_GCM,data:nY/mBtDez+sscIs5MKv1vonHDHBYBVMc,iv:XT4B9f5NfoprOy6zOQpDDogWucq9Zcu3/lNgm93q+q0=,tag:vW4oyJFI8MUZ624ViIeOOQ==,type:str]
      value: ENC[AES256_GCM,data:gJ3kTVzSo1MNNxDf,iv:DJaJNhXkRTXhRfuH2X4u9wL3wSf4YGsxxObqISXJNjg=,tag:XHH3CXJFNmfgnZ0N8nIzJQ==,type:str]
    - name: ENC[AES256_GCM,data:1GEBdL296HZ5hipkpu21BPKqmQ==,iv:Q5enJFcu2JC/80/7/CnO8gF+hqruzDMqPCr5kvYdcEE=,tag:Cd3oMKbxwKRbfrEEgpPN/w==,type:str]
      value: ENC[AES256_GCM,data:vf+/Jb9DzdjHCK7A/jTd+/2ycqDYdUPxCOcnfu87jWMVPXyuHw==,iv:6P2kng6SsWOpU3OiEdF8bfKeSppti6s2HA5Cj9tWWgg=,tag:4D8FY9wnU+B8SDRuJWxFag==,type:str]
    - name: ENC[AES256_GCM,data:daetfQzbtccCyksSX19+Pw510g==,iv:Ncrs/tSPkbBEdCdp5aTihrQe7uB91ii17TcsQ87p7LA=,tag:PFd2xSh0cJIZqahBVh/PXA==,type:str]
      value: ENC[AES256_GCM,data:iIKwwo61TM6CIQWLTlywcuZdeymFXxr8NADqDhFZA+MYxIqSSUbluvH0s1hQ7OMU9PWdP/8JNKX/,iv:E5PEUSuQlROwZ63b/30fxdNiBiSrFRbV2i2xumjIMHc=,tag:NwRFpGxgk2TA0vv9KWJExg==,type:str]
    - name: ENC[AES256_GCM,data:a2CPT42xYiZgkMmt3pdiLbG4oA==,iv:xDHDxNNFwUk4H8uEmxIvF4PjnE6hnnUsSKq7EtE95hY=,tag:56neEBzt8guTYFYmq+65mQ==,type:str]
      value: ENC[AES256_GCM,data:QGBiMp7YgLBjSOxcKCy+1PW26qTU4WIAGIemak8jN1oU,iv:aIiBahqFqrDsOzzGdfF63khUl7tKmRZUCr06h27kNWM=,tag:iwMfTDsunsiti0vNpIXp+A==,type:str]
    - name: ENC[AES256_GCM,data:qWokKGSJOv75r94iqcyRL/nlwF3HfEw=,iv:qJWZrVM18TKrHrjVjOFCqgxT9FdCBrwBYQDhUrcUI7c=,tag:n4zGE2ktxYFFHCvizKTBxA==,type:str]
      value: ENC[AES256_GCM,data:zw==,iv:L9HgoCIwTRpxyk07TiIQBHI1T681M6i+92wc04pyY5w=,tag:ubDKujCnsPS4dLm3CbknqQ==,type:str]
    - name: ENC[AES256_GCM,data:MjSPnh3nuMXR+S2fslGCkOowrQs=,iv:K49QrXm3eD8buxrvHISH+ndxmEHVvqydIpRbMhpEoi0=,tag:xaYGBGJgpDiTA3DfvpoqZg==,type:str]
      value: ENC[AES256_GCM,data:/lHk1WNcCNnhv3sS,iv:+tt1IRNoCd12+KSWZrKC8oU3jwRdw8+gkkIhkGUzEeU=,tag:h/Bm0GnfdeBtrTTaAGun4g==,type:str]
    - name: ENC[AES256_GCM,data:622LBAs4UIk=,iv:pNIZ3EHEMJP/PiDhYRed7/zuwdzRjAChY1oe7jZ8mtg=,tag:SU5A7eCTGRFgASMYm3xXFw==,type:str]
      value: ENC[AES256_GCM,data:cySNTf4GRmqKUbsRMHcK45n5tBJIVNbcDnhBSWbtEjm3m277iDLv5oY=,iv:3CBXP2rzk37swfE/cxQzZbkYcoT5UWZdNysumOGQydw=,tag:8yAeAm2zy0B10Kce4YT5Mw==,type:str]
    - name: ENC[AES256_GCM,data:bQjT9QUHiKo=,iv:NVSycEvZOOE61wHnvi8WIDrFout6Xsk6PbrREezk2f0=,tag:9Ee3Vnvxsn9IKZxJMGddHg==,type:str]
      value: ENC[AES256_GCM,data:7IumYg==,iv:0UPrflTRPCFnEAwHVBSF/zWzxP8tEmb6uPrpju63SRQ=,tag:dSOjkIS6dxVm8J12rfm5yA==,type:str]
    - name: ENC[AES256_GCM,data:t4D4GvExHGlfaVDt,iv:2CNzXUsl9pZONjK4Imota2TVNTTERPmY96EOjd48Ht8=,tag:P02XT/z40rMNvWuuHyjYOg==,type:str]
      value: ENC[AES256_GCM,data:eLTgH4tfJEMgh5/H,iv:HYVhccdWjfi1tqqque3OCy2Rcvbg/ricn1GMvAN41Hc=,tag:ea5ubgvkNm3hgRRTcQTdYQ==,type:str]
    - name: ENC[AES256_GCM,data:b/Gp7pj8piZO+KQ7,iv:7LYEAjpjzGl5btvBuvtumMeCIorR1FnoIuEotgBRDxg=,tag:fM0nPJR081h4/+6wfwLegQ==,type:str]
      value: ENC[AES256_GCM,data:xvhqRKaHA1pOT83G,iv:8BSlP9JNeFcClY1pPwXjYB3XPmy9KUPQKP+4ffI8sLg=,tag:0S8x+Hj3TyWYRB18SN+c1A==,type:str]
    - name: ENC[AES256_GCM,data:rOnPa8StdpFbtr8=,iv:Z9SmdtBxqFkmGoZaq70UWNmmMG+aEE2La3MKn0Pipyg=,tag:8HNikZ6TKYvp/qWHLfS0tQ==,type:str]
      value: ENC[AES256_GCM,data:/iFJCCE1,iv:sMT3yO7YcvqBcIc0p1ox9uMqqcms0rRGhaXnkMouEbQ=,tag:j6LEMgMpvzJI8BQgoNmKkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFczBUVUtnWldqQk93NE1t
            aWhZL1FRTlNydzhaWlo1dUo3NVhhWUw4K2c0CkJUdytEZENMYzVWRFN2VnE1eGU2
            L0NlUGxpbHNXZXNiWXRSZm13MzJ5WE0KLS0tIEVuOHdrYkEzd3Zjb1Vqak1oczJo
            bUl2dXdRS05DQWYveDU1Q1pLaEdpVmsKfXLSI5vs+WGuJytmapxtycn7VG3LsSnm
            tJ/4ZqScGdOck4r9gW2jx/cmY9zDUZKItHgv5zLm1ewYyf03deIA4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T10:22:27Z"
    mac: ENC[AES256_GCM,data:PtkUtWiHYMKFKqyv+J21zD9B8BpwHqIG7gfyFGuC4ISMS8FnGPbvnzu/GG9hpKMhBIjMjZbxgWwf6KnOdm988JBPVpWbmXPO+NoebaDW6YWmgwQkVLmhZ1tcwdE0Ydu81YxkDxFsOEIRkVCK9JjMwFDg5qilZ+vlPxfxmgXbOC4=,iv:t3fs8+YZfS4HMbVNJ/ZHenS79YGA2FPEinPEgEFZY6Y=,tag:Ed3b2hJN61uKvcwcmXpjhg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
