image:
    tag: ENC[AES256_GCM,data:fICl1ueC,iv:+PzKGTmg2Xm4pZzwG8707agAwaTVG/n7sfdf0XlvVhk=,tag:FigHQMZ30oeN1ffRKQdQnw==,type:str]
    repository: ENC[AES256_GCM,data:ic5Mfv7iYeHLLLGyoVJOZhncX++83gxRfqlArt8c3XiyvNMBs8Q=,iv:Q35lojCxzjtOxwStAK0HB9mI9FQ2gjfASCYP6uCpmGU=,tag:glVIJtHphGqJ7F60PTUzlg==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:mQNFMg==,iv:Hv8Rhk5RtYFwoLvwJb2F+t6WQ9ui7KYR7ykcXQPsZiA=,tag:MyGmsXtPorR2uv/bjYOy+g==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:U0XT1tCOV5suIr4UmZ8Bno4nx28=,iv:89vY9oyCCwVL46CysnRmxwcW8UpKh0z8CKJREclJ83c=,tag:0tz9/oPz1HkFZ5VwhmVP7A==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:NddjM3zeVhrptbDz,iv:hoxNa0hNMeQ+ZP4PRgRyOQp6hFSQ98/YXzrgIH78e4o=,tag:5hiUSf2BQqAPSbDYQX8JaA==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:c3qM+gBPwi6jBTh2,iv:S3qqk0k1HXTspaFFCOHobWUB0rrfYexUFwjnLJGftbg=,tag:WbdiBsuqkDYyBnW370lmzg==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:VZooCc58RN4VtyIv2N17SYUmjms=,iv:ljyK2imD3fwEgnreDDCicbMCSzE6CadJeB+ClHpPXjM=,tag:hUADKg48FuEKy5t2SNncCA==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:HVuyzczX2eE0wg9QaIM0V4Qdmxnols7aEXeabSg=,iv:K9q55jk67PnAcHjmSVi6umXsR8p5l4B4kVYV+TBn3i4=,tag:rQEk+7XmdPsyOeJev57rWg==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Ww==,iv:g9OHTAQe8i/80OW1YHyElPWgx2n4Zst6bPbrnROT8NA=,tag:lOtL/hxbk/W1+c1DWWjTJQ==,type:str]
              pathType: ENC[AES256_GCM,data:+IURRxXd7tmcuJuSVE+o4VDTdiKokQ==,iv:ugAEXJcqb2DoBRPl89Y7Vb2eBwpikdZeDagJsWDWaeY=,tag:2j8Vmp9v2OhK5nHy3WiLug==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:40TKfTvNfN7u+0nENxzvP3PSNkdSdN274QM7Jvo=,iv:ivUbXzyYjM8ojwp6zz6ycBjRgf0Mish+k2f+2pRsrGY=,tag:j0ABBaWqHFcrcTpHLxbHWg==,type:str]
          secretName: ENC[AES256_GCM,data:cAaIZAuKwCCTwvhfzZghtrc+hGE4SsJJGR+/pRRawKrpGR+Omys/,iv:ONcUsyb3lJ4xl15EKGHpAvg4PAj3bPKzUmfTcrmuGTs=,tag:H6I+YtfBfGrsgZtzjOjybg==,type:str]
service:
    type: ENC[AES256_GCM,data:GTB5vOKBYPw=,iv:OI5kNkNzlvY2lOCgIaOWuehtPsP+Z0F/aQgRjusuLZA=,tag:w+R0EVW4/t69NN5JGYlJsg==,type:str]
    nodePort: ENC[AES256_GCM,data:e8oSSzg=,iv:XhIIuf0U7kR6iR+fQSCxi5IvbpMTG0uAHrPqMZcbSHs=,tag:BYww2cbY5Akg6SBNY7AoWg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TVYrVWhDSTU3UFVnRWwr
            ZlhSdlFLelJ3NVpUV3NOWDVwS04xYy9Md3ljCjlCWnA2OUI4UDladXU5ZEd2TURJ
            NDN6YXhVZzErWUxCZmtld0o4SDllblkKLS0tIHZQeUsvaWIvNWx6VXF1cG02WU8z
            bGhFd3Bqc0RLY04rRXlrVVdkbjJxWVEK8zc8gKQ6zcr2xwHkJ6RHdy579Rpfj1+3
            HgFT8M7sTHrkia78DyADJNbkMnzpDhMh3AiUeaNHCBpT+yqPHbYhVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T21:59:34Z"
    mac: ENC[AES256_GCM,data:yQiQkQ5aABSYPz8olADEU02ijsygCyvxmB/skkQ8mq77IQhpgsJiK9Yr4BiAyfJWSxAI8U/wzNtaBWLfYI4E9c/H6KDr0JHrDGC78Hk0cSJR9NvrJqY4Zgw0yn6ENwugIo4IUHqK/z+2j8msBGN1pAsZVXr4o0gaTN2Rms+UNv0=,iv:FfL/JynJNEvWVVqzIuqw5RFoX90QU2KbPUc19+1zYXM=,tag:EYgQrexVfxYl2q2Fuy5AZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
