image:
    tag: ENC[AES256_GCM,data:YnFLcLCl,iv:gX1WnBQrMdownf7Kk0rJJYLZsX/O8x72uapQchZiauc=,tag:0qH9VyLETML8NwKjbSktAw==,type:str]
    repository: ENC[AES256_GCM,data:JdbAOMjc2MW5hIJIU/G8QDnofZ4HE0LDV4AB5i0mIxoO0/NWNsg=,iv:8ZV1DH/fT/quaEMPRD2nHRWR8wTmcchWvh1PECJh7bU=,tag:OWaSCraUfeWXJd6H8j9EPA==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:qayyCg==,iv:GQLKkfheczilhNKSCL1e5O8NxTrxVDd0dJKs1IG1Op4=,tag:HkE+nuUguqkQbQUC/o0Fmg==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:RcvZa3izjXQLL6zNpzkdIyS9Nkg=,iv:PXtYmONaI4kxsy01u/7/nOqrrzHaYPxsJ8WQQIbcmqA=,tag:c/4fKR4ZIOotBVb4DVv6QA==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:oIAo3V7N0vDrn1FB,iv:ANNYjXCmf4M0GK6kUgV2FJ3BWgI87k0EKobOTt/Llxc=,tag:4MiqLlV3gcZHS+8zIXSh4g==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:n6N0NHXNwCD40Cil,iv:vVbDmIRoTAJKvrjiEghhEbz4X/rWq/aM119LXhyHcg4=,tag:7VdHZ3w3U/iYaD39SsKGIw==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:khsY5DwZw8AUCI0+KmXoCOCJYUk=,iv:y96TAD6QtaWIRijPOL5XtiZX8hB528eQmT0NP11VecY=,tag:V8hdT4n9BFojGRUdyIlY+Q==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:EuEIv8A1k5eC5sJ03MHte/aLKXMEL68pCuNDILo=,iv:HUDwxdZjzza5QUlytK535yV1tbE5lY32/daAmL0nTCw=,tag:b0Yb+bc5LCBKp1HQrCnXeg==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:dA==,iv:qn0fe1S3ehORNA0Jje2gIQ/RfC/TFFCq5XTEEyEwwt8=,tag:XRkRexe/EMHZFbd1omedyQ==,type:str]
              pathType: ENC[AES256_GCM,data:DVh05+bZ04+tptz9tvXC63Y4X+aH1A==,iv:IsfbnuAVAxNShSJbt78/vnWJXeRVL/VxD0qoE4ZPKGo=,tag:Bt6djG5PpUG/DM1gB4QHhg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:rjQds79PpYL6VEOc80I7GI2+/I9Jxzyp2EI6xok=,iv:TuamcdfmF1Qw4ACDlo/b3UE1y9l0sN2D+EzghbozVyw=,tag:85KQ/E3CUfy7vQG8tmHUaA==,type:str]
          secretName: ENC[AES256_GCM,data:EWAPYwAFh3arMaMagY8vpgBazOf6RDkW0satRnR2lvIh19B+7Hve,iv:myMlhh0Jfc/FQX3bCV4o4nJCtA+vGtJtDcKmt2YShIM=,tag:H99iE6mmnhKoRGepgzh90g==,type:str]
service:
    type: ENC[AES256_GCM,data:/Z8LdYVYRis=,iv:SOyAvTeLJzZPlVOvuLiLnb2JOUjMdrQTndntP2JwQOE=,tag:1WLMXWuhNhPgZl+YtWf3YQ==,type:str]
    nodePort: ENC[AES256_GCM,data:FHrydZk=,iv:YFIQCvLhCZLg/lIowi3pSRxNE8sIbhfRMap3t/IyXmM=,tag:1MD7ap3otyf0IeVDiGoVJg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SjZXdG5mV0pOTWVBSG1n
            bHJBNDV2UHlXRlBwUm0yUVZrN2tzT2VhTXhFCmVPb3NSMmxvQXFuVjE1YkpmTVFY
            V05EVEhkZzNOM1orQmFwenR0YlVQTEUKLS0tIHZBWGsyS0JVaGRsb094S2ZjVFNo
            em1NWFhNYXR6bThXM3NDZTlObzc1dzgKUvdgJ5jesysuFwT7MqqcDsxwNbxD/XCi
            IvCtkYafXr9pNswXRRyw86/OAF5B7P2YGVm5x21IMk+5rxRrsTqXDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-09T06:32:30Z"
    mac: ENC[AES256_GCM,data:ky/Y1m4DVt8MCo7g+4pxJvBb1FK+Qgd1dtUOrcy+1Ev3V5gY+E8EFOoj8gan59qkbfsGOMDzCV/JS28uCPSk+ncLLZ5kkke1FiyO5uYHoiWaPhJlcGWdMLmA3mGy6TqjtjSZMMMZcUDVTuLIluNqEjUpawT6qYSQAELgZZ1Jo/A=,iv:8UNXRb+eMHT2VFQldUitO+hmu9T/5QZa6B8pvk833CQ=,tag:kSipUGRNYAFBsEjH0kcmbw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
