image:
    tag: ENC[AES256_GCM,data:e2G/zaa+,iv:INpwtjpD83/0+zWmIuLyhn8mS+w/kFxF7kv8wkhzuds=,tag:WmaO4t5d5NsKr5Evy+Sr8Q==,type:str]
    repository: ENC[AES256_GCM,data:rifMAKFW/mieU5Xk9l4dpvv6qzcOIvrHzK/v8tkbXZtl42wKTwc=,iv:FcgMB+NIPKr1jcrs9fZQYYc9PRxYL9JAKfNioLoJQZ8=,tag:FCNZUS52yorZyQ+wvFZ9Lg==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:1JDu3g==,iv:w0MvkjgyTonsWoUEMTooxgGucHXacIr1AaULdpOhcWM=,tag:mSKeuGUddmtiVDyXpm8vdQ==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:Gq8YDV5+N23J8hr58pz/c1UoU5k=,iv:y8r1UTgXXmUpMZ6uD0YDMzj9oYyiWQ7n36kXX9sFyJE=,tag:JrxULtqo2/EpTEw2lvFa3g==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:eB6txFr/gAF6Diby,iv:6Q6qk0E2Xo82AOnBUfQJL3NAwDgnsK8bHjTwWvY2GM4=,tag:kRogokJu7DMTZoZOVBrMIA==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:IOG1Ln8v5oInqX+j,iv:U+HDp/FJb+Tc3a4UIROeVxvdBXNFN6Aybyao5tigj+w=,tag:HStrKzdyRYGcW93sweKTSA==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:eeP/Kxa4lkv5KSZ1gAEnp/qywqI=,iv:3xUqxm/7ZDoXx23Zmx1zOqPYe7CR821n8lmru+EDBqA=,tag:ZB2szfQOy3O32U0KKxTBZA==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:e3n/UdOiHYO39d7W/UVygUCc/TRBOIrLaNVKWn4=,iv:kJuvaKMSi6me1tZP3bJArSf8Ysbyw0GRVjRw2DCHGnw=,tag:55+tf/3Kp9Xv2wz1UzWnhQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Mg==,iv:HR+NFuGavXcNip0Zfn1g6YAg8XbXKgL5WywzRtsPG6Q=,tag:FEV3m8xi9goh578ueHNC6A==,type:str]
              pathType: ENC[AES256_GCM,data:PCO6YZgVuhp4hGdqCJqfxN6XKoixIA==,iv:tMw750nh3pknV7ny+6rEYW3/90QjN8f3330FYO3fumI=,tag:Ac2lRU7inI40xKEGFsPemg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:Q5PGcWrudE6twIRbXXhbkNL7jlVpfhTOoikzdbo=,iv:yYnGpO/vhVNGQPKJsEDO7UCBbbWokQWG3FtlS3U0YV4=,tag:QinbUJPBtqIYYg7N429alw==,type:str]
          secretName: ENC[AES256_GCM,data:UGtdkRMWigBxLqRnkBu04FUe4d57GgzDssdbiZPrD3QTz59nNynF,iv:x2nIANLgFVhwMeczHhfsznNr2reFHMt3KsUXvRu8A10=,tag:jEkTc4HqRR1powNrJMyCuA==,type:str]
service:
    type: ENC[AES256_GCM,data:G2DBgQ2pAEM=,iv:QqDo9Tf+7CMzKa6w0uFVQ8r/dsP6mX3Lr21p/WmUyP8=,tag:fX20paX8wW5HW8lcnHgHNg==,type:str]
    nodePort: ENC[AES256_GCM,data:1x/BViM=,iv:fu8kSWLLbXOPTOgngavnDkQjy9g0sLZKOFFFxscogJk=,tag:MocfoTja91wAg6DekPj/Dw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR3AwbUY0Y1czTXN0YUZG
            S2F6Z2lkRitSWWFIZDQwWnB1ekFqL2wvb21JCitKalN3cURFdVl1amNmMjFsajNS
            enl4dFd0Rzl3andMN2dvdFpoQ3hENzAKLS0tIDlUMjFQU0FWYnpsRXFuREhnT25B
            T3lUYmIxcnExRXdQMXJ6SS9Dci9EQk0KJRiCaY+xOVG3WUxAjvIRpnlaCp747Jtw
            D/XbgSJVgzLCYrPjgV64bTq+jBStXV/672Ee4WbyP8j0xxjveruX2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T21:31:11Z"
    mac: ENC[AES256_GCM,data:bgaoXlUooH41lr3tShczp6W/eWJFFc0pei9EFkH4658JDN3q+zgcN/akwj/cMKCRixXhd6TVb8+ssXcNuhb2DLJBC0U3PdGBFYsp0mzF85E6RSBTwiIuiqzz2nspLFdelLv8whqiXg4Vsj5yfg3/iaXG+wZ5b77eRPwpbebO5Do=,iv:vfoLs2YwRerB31ryPwJSHXly4CH03bdjJkAOgq2THsM=,tag:afFyJ/5/Crm3I3drZUOukw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
