replicaCount: ENC[AES256_GCM,data:TA==,iv:BKqI5P53+pXQod0iglPQUJu/lnSKdPAuvtWELfkosuo=,tag:sHkSe+JA8Nm897gJm1g+lQ==,type:int]
image:
    tag: ENC[AES256_GCM,data:9mE10nIj,iv:IRqrpmDnBwTe89dPzPkPQbVYZ5fuRvJub5cWkLMt6B0=,tag:eXbh+LV/kvpipkt330wslA==,type:str]
    repository: ENC[AES256_GCM,data:F3HWQwkfHdVH1hT1CPZsSojDgxNlu0Fhqgegslp/I1NCEg+wmwpT,iv:agU7+QJvT215svtGpm6qIMX5oYNN1OwNM09Fo2AVpe8=,tag:0RI/2/zH2QpGcwTXVO2fnQ==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:grSJMw==,iv:THwGnmks2Sptrd5R2J+3+6z4s8giS9OeLeUKwi2pyiY=,tag:vNT6nc+3VwvXN/sbi6zdzg==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:aI2KG762WnSKWYYkcETntwRPLM0=,iv:wUw60pX/KuBu1YiNDpqMeGvtMZ+VR1m5L09AnZDrxck=,tag:G55QFdThNazTwlr+RUrYeg==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:CRRVRBa9Cs8uiJq1,iv:AwjfNc+iB4/B/TE5bph7fMkKEswAq5pbelZmfySfQ5A=,tag:1BhSRFUTH/qIXyzeDTgXlg==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:2+NkoOPMx2dKwyD2,iv:BGtgUP0G5SBlxS0H0YhSQ8IdxrPa73cprynObplL+AE=,tag:v1C09WwSrzxaYN3Kxw4KPw==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:gZxS6gpqiyxCkkVMF7o4lFQmuoY=,iv:BCankKtiJNDU0NCpokfaiz5g6b4qEmP+eUuCBiTeC+g=,tag:3oRyrI9jEeWWIxZ9tXYhxw==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:YcLItdLD3VdbGgHjTMsi0SPglKcmdyWdi17fwSs=,iv:4lqQ/XTk0BaMRps6Uj2VNmKS53FyRNqy8iNKXqm6DdQ=,tag:+1V6vz9Tyjl+/i0WBIkAig==,type:str]
          paths:
            - ENC[AES256_GCM,data:LHpXmDMJm2XWUGnVYR32m4uHgD6RXyaqoZCDAzsl,iv:7hnshBZLipGkCSyjPbXaeJOLuyuS4beAwVSpzgJjABY=,tag:2cSCbkZeSqVF7RRirmQx0A==,type:comment]
            - path: ENC[AES256_GCM,data:p88bvg==,iv:B/5RMJ34DLrbOCGQdNrD294dxLyCrmAxdoMlHqQB8B8=,tag:5XadrHjzGvAy+NP0G0SAXQ==,type:str]
              pathType: ENC[AES256_GCM,data:aOOnWBGvGM3/7xec3WerJ5Nq+euI6g==,iv:iQBQxkOWGWCN0CBOnnbsQZ4tb+u1G+sToyElk68IDaY=,tag:MOFNaS+YmQnfTg9/HgOH3A==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:6nZifaATQXrcB/4shOQP8uXcHH7Hwg6KgD0lx3U=,iv:5zxpwqs5Oqvhvp01o8pmZl18U/jmKD7SyhN6D5S6k9s=,tag:8ABtN/H0Ang7y9YCT+mQzw==,type:str]
          secretName: ENC[AES256_GCM,data:l2M4lQttmUkaOzF7JU+0ahzt34gm5orkOblexEFrn/Bkww/oBBdY,iv:3R9m1uq0Fc7B+gMsMG5GEtLzj1qwFVZjN3k5FvosuGA=,tag:Qz5ifhfa3csIYixw8H+I+Q==,type:str]
service:
    type: ENC[AES256_GCM,data:Yy43eAObCFo=,iv:krtSR9tJBNTxN6c/T/X0HPKTPYk5TsfzVW4Kq7wiles=,tag:Q/QAqnEJ3eHO8QrU0/4tew==,type:str]
    nodePort: ENC[AES256_GCM,data:kuGakNI=,iv:Onx6W3jc4dXT9XQ+BnrD+AR22UvmKEwJJoSJRdBxkaE=,tag:psY64h/KlffHMj0waELkqQ==,type:int]
env:
    - name: ENC[AES256_GCM,data:KO4aJVqJgk4=,iv:0+PRbzgnJ1saqhk5Jo2whXYWwg3v/EoXlf7ZQ0up0u0=,tag:aPMsDBBMABV8yW2hdpg5wQ==,type:str]
      value: ENC[AES256_GCM,data:mZURZudu4IY=,iv:RGKJRlNeCT4en5mIVFvaBrot+sc70R+OpszjJnx86Ss=,tag:6+5mKnbvZcYAOWJjvMIC/w==,type:str]
    - name: ENC[AES256_GCM,data:khuXMBlSg1u7404=,iv:Us2aHOpTDSxQz4b7cK4t054g0v7GMEyutR9KC3A37FA=,tag:pBn/63lgeZGdKDswI55SFQ==,type:str]
      value: ENC[AES256_GCM,data:39VINS4X,iv:VxaV2hjBio2/DPiiDZ8Ie6+LrucFghEF9LxmhXV936w=,tag:Y0v6GWI1NJWJeKA0QkkytA==,type:str]
    - name: ENC[AES256_GCM,data:bbR4SuoRPgDRq8oVDZTq,iv:5dfyXAY388jK5HvVaMy9PtF5oAIi/PrK1da2nfMhJvQ=,tag:xJGNVgjhc9o90ydf99FC+A==,type:str]
      value: ENC[AES256_GCM,data:f2phWw0BrM2U9Kyy3jbjsd5U1tY1B3BaVLtKQYd2qvX7Qerf0zmQnTFHl/HG,iv:/uI3wq9yI/Ak24LctVQZBkluFDxJENCrFHQUO088sP0=,tag:dv9RZo9uh8E04VsT/BpkNQ==,type:str]
    - name: ENC[AES256_GCM,data:Wv2uzfC8lE349CLeZeH0,iv:9axpfJJLhcKCp+hPjRZg2NmbvYr3RHpJfOkSjBeAfpM=,tag:h1w7U0Ch+HmMXU8C/PD3Nw==,type:str]
      value: ENC[AES256_GCM,data:/K+62g==,iv:cnjeQpBTgu9h6e3mLNAezaIMN6zPgIlnGt7AV2cdXHI=,tag:GsnFW4CP80YgO+rNTfakLA==,type:str]
    - name: ENC[AES256_GCM,data:HFe/r/GPxck6TzSLhw==,iv:D6gIuFTKfk2n1LXPOHSjLncRqkerHmpbmO93xsEWJuc=,tag:4OVUSEOOekMeGysT/NzXdA==,type:str]
      value: ENC[AES256_GCM,data:sw==,iv:lG/z0/JHbO04VzojkTSlCMoFf27GCOeHLDhSyHplEfs=,tag:Jvj/BjLTuXSuvxHWIWl9Gw==,type:str]
    - name: ENC[AES256_GCM,data:xIwKbY10WH83CE/zl8Ih4aPA4A==,iv:JAbSgOJIeS3v4lY34WG/7N4V2Kt1H/7Xx97gOEZ5KU4=,tag:RCl6l8F6NWPmN7AC/s0woA==,type:str]
      value: ENC[AES256_GCM,data:bWgsZ5+3+hlG1fEgHdDJ,iv:bFX8bJ/oJD2MtTAHOHT+CvhMhFAgzTc/hgEb4SOkzu4=,tag:9Mp1876NON8936XSKMkJoQ==,type:str]
    - name: ENC[AES256_GCM,data:jOHs0l41q2/4EqDwJz4=,iv:tyKRLv10d/6sGcNNEt5GPW6O1jfP9GhlKfBKX16MiOs=,tag:47h/iAeJEyXYRocLt9D23Q==,type:str]
      value: ENC[AES256_GCM,data:Hg==,iv:CHLfeKKFVYh6cKCGdZ0ExWU1ZwvqqOTomdjiGJZ/GPA=,tag:TVcN1AZoM0w9sMopYZzGew==,type:str]
    - name: ENC[AES256_GCM,data:6Gia1+Iig8toEGbrrR3tp2X6S2M=,iv:/q2XVA8D81zqZBIuFBjhiBqKBy34mtD76JpsVAHylV8=,tag:+el/XLyk6KQYtXLlrWLC0w==,type:str]
      value: ENC[AES256_GCM,data:vEJRtf2MFx+rsoW+XA/1kzm0cjANHb9Z7GMlV4Gz3A==,iv:ZUA8h7LXUqO7JOpL5BICy2vKM0pP5bao6bGBmgakAs4=,tag:xgV2RxlVmtEu/upozHvK1A==,type:str]
    - name: ENC[AES256_GCM,data:LYU8jlJZn+mg+gB/ZBjNBA==,iv:L7jwVy5dLP4RD5xU6orDrGbWV0AHAeUEeCmfYWJaDLY=,tag:NjXZJRmgPUV4+LqahUqAcg==,type:str]
      value: ENC[AES256_GCM,data:rZPecJNObLA0GdCAk9k7py++uPSxHfEH8hne2pUQsA46D6jl8UskThnQFUrv,iv:sY1zOJ9nufWR12iyp5jWicx6WSLVtkhVZjUnVoiKBlY=,tag:ZD+MCA8xb7t47QomT1T2uA==,type:str]
    - name: ENC[AES256_GCM,data:4QMnoDm75HC49DXDoyfILw==,iv:yTXH5kf59WdhveIH8XKGgX9xPhJZaf5haDBXxJne/uU=,tag:cmf/YnsG2LEPKjtB8+NdRA==,type:str]
      value: ENC[AES256_GCM,data:eieMeA==,iv:56X8LV91V3j0mAFFbyA1DJSF305OOhqt0tmDhI09Ovk=,tag:CS90yGRY8yuc3woSAmcnQw==,type:str]
    - name: ENC[AES256_GCM,data:sR9A5hVIaVm0UNkW7Wk=,iv:HFQQrDvRGO229cT+chePCMjH5h43YFdnWtepgKxmThE=,tag:hbJTKdq2RwGAlxM0LK0rBA==,type:str]
      value: ENC[AES256_GCM,data:AA==,iv:CBbEVUy+Iw4TZtA2WLUUAnhJMdHgAMd8ZXpxj0MSWXM=,tag:hOlqFtOVR3DKH7kUKnrRPA==,type:str]
    - name: ENC[AES256_GCM,data:2bq1i40L+SYl7B5d5ERkCw6beYk=,iv:3VZl3uIh6MZyhMxKU+ClehRS+j7wfsXlHOUPoovcjF8=,tag:ijfSpP28xumfhOAbTl9raA==,type:str]
      value: ENC[AES256_GCM,data:6p3Kji/RUmNoYnBAPZc4,iv:M+OAkQ8hXc/M9/TdrdWrq/NKWl9U0Ia6xngUol9+i2U=,tag:X0m3MClxR/lvAjearL6NEg==,type:str]
    - name: ENC[AES256_GCM,data:hwNyCX2F/kjQulpwoTzR,iv:AyYQmuv4AC83pFKvvMguha/HvWzd0ZlKTnMLkbV1rFE=,tag:a+SI+PMYUu9ao1CcHPXwtA==,type:str]
      value: ENC[AES256_GCM,data:Cg==,iv:2fc6SpvEzXAJDbTeQ+tvUkmb3Op10urql9syls4SFU8=,tag:4AxHqMXPBA40yRVkqzQEyA==,type:str]
    - name: ENC[AES256_GCM,data:Ck3oeS4XNSrD63/owifBe1ARXeHP,iv:xPUjvgLaQcl5a4oT2WOZMX3SfNv3PPd+nSfh8p5gl7E=,tag:m+dE8HlXIxw46E1DpiDMzw==,type:str]
      value: ENC[AES256_GCM,data:dRO2X4CbIJgsIqF6ushFySVpBh+RCWSnegyH3JHSOQ==,iv:Y4F96Akvsj96gikjoGSqiBGZp+OUlh3zEjZiAy3C2GQ=,tag:Tx+5p1K/cLNleqgC9WY/xg==,type:str]
    - name: ENC[AES256_GCM,data:y+hOQ38+x64=,iv:JZLVUH/fhRz+JofDaeKhV+cWE6x0cGXFa99YT6C7FnQ=,tag:h8qMXlSfCyrf8ps0MAXZxA==,type:str]
      value: ENC[AES256_GCM,data:Tq6Y+cWZR4PiRJ6ERZ34kkEypjKsF4C+R6m6JAYfFg==,iv:v2Q3Zf0MQU5dpuuzn8Ti3M6QhoCF/4kMIo20ohItmEg=,tag:7DMSIxD0376HIERCEV8oYQ==,type:str]
    - name: ENC[AES256_GCM,data:qABeMHDji46h5g==,iv:R495KL0RxF/WHQD2dIxzJYA2fyCl1mM7R6LRHLJEluU=,tag:szoLx2tmRZ7vKo2fQzR6fQ==,type:str]
      value: ENC[AES256_GCM,data:Q66SbssehA==,iv:c2Vg5AM9uWS5KlL6vMte21AF7yy9iDCNUvBSiuB5JlY=,tag:LiGlmDpPIi2ruKlp9u8cgQ==,type:str]
    - name: ENC[AES256_GCM,data:9n2oDeDpCcfvOCwekqzTcqo=,iv:IoJY3VRuNLqV+RKZP8lCxIijZOxe7ZEz2wG0LNiDaNo=,tag:f3vAcm250k8/YlleizyhQw==,type:str]
      value: ENC[AES256_GCM,data:Z3mKu2mrY73Z4bbM2CgTHdDqHWf20TbvbA==,iv:mpOr/b5rO4y7Jz4fld+neAc6UoCH1A/rcWhF0USYKFw=,tag:Z6shEK2NIGXqbp4qSyPLCw==,type:str]
    - name: ENC[AES256_GCM,data:ol5yehSeUeoBlfqOwjc=,iv:RDn2ZA8YvXO7DeY7VxXSpawBjmRlWeTBxV50q+x+cBg=,tag:AoILjd6dbHrTuTg8TcEprg==,type:str]
      value: ENC[AES256_GCM,data:MGaNiFAHyPxntuZTL9tOGkh0UlLOW/erwnLBhgTfVCUzpljkiPAzYw==,iv:HwidrGz1UUztrMSpI9L/RO2NmhBkhFK1ulTH/inWlAM=,tag:Sn24w4koOqj0g2YBw1AVhQ==,type:str]
    - name: ENC[AES256_GCM,data:mh48zbyB6NpEBvAKLV8=,iv:KP38cL6eK9TJQeu2JlrYtJ7EHVHV6IO5ADl6UWLt2s4=,tag:VnVsv9uamBx29EYkWR65AQ==,type:str]
      value: ENC[AES256_GCM,data:cNz0pgySCZq7npSE6qfrG2FQy11u9sNiuEnMHg7H4oq0VGtyGQ==,iv:sE4Khr6FXuJjaCnP/I+1M/paCmhRwe0XRP8EeMBiOwU=,tag:Qm4YsQeOUcXJFRM3610zgg==,type:str]
    - name: ENC[AES256_GCM,data:K3q4j6eYSoqb1Qgk+uqt,iv:vfegyqseBV+tXJV0hDn4RBn4V6n4LKjUyEE6o0j3iYw=,tag:PzWLmVgV4kdn6FyzlgdTcQ==,type:str]
      value: ENC[AES256_GCM,data:pNaaGw==,iv:ahFOYAoItOxdFjGOC096ZDIqc3tTSWpBfz3IwgVjwXE=,tag:dmtA5wqpe89fz9tUHk5efQ==,type:str]
    - name: ENC[AES256_GCM,data:1a5UU7fBB69cyEJoh1Fb41DU3Q==,iv:MfptB2d28BtywDJSnr7sqe9YSZG2rrFjxRf3S01ADi8=,tag:Ug4Vt1wzX5bKL3553ksPpw==,type:str]
      value: ENC[AES256_GCM,data:retwu8hCd3ElADIs,iv:QQxjBLDAqwIccjlJhdazeUomTOXCLnvnkCheoVz655k=,tag:NIIxD+3y7im35xqpqMbOXA==,type:str]
    - name: ENC[AES256_GCM,data:CC+DX+G0pKSGWGtJIQny5WVVcFW2oTRl54Iw,iv:DNQZ3ssTgL73T7iOXaPugUVpbZkMEHb6yc42RJczS7E=,tag:EVbD4fjQ46viM7Bvr0+Zig==,type:str]
      value: ENC[AES256_GCM,data:moJrTDORsl/YXMyA/6faJe67El+HCRid2TQfwC/ACvA=,iv:DiU7PHdAMvxt7HFrlEEfq21B3KWJAN7PrSKwXtIgicg=,tag:76El1ohtY5A3lauQaSsw+A==,type:str]
    - name: ENC[AES256_GCM,data:3e55tKImueCf0ijgDN8h5ykqp8B+VvbxVYK1,iv:8n4Lg+Eyjwfqikgst/3BH3oZVHeTYgwyeCYz1av2X1M=,tag:bmJNmY3CmayhtsuJUZKsBQ==,type:str]
      value: ""
    - name: ENC[AES256_GCM,data:Wy87Bbw9AsOkn3m3rWVGEncL7CQlIp81,iv:PZj92xTaSN4WERBBed1XkSnLJJCl8Cisj1CWZt3yjuQ=,tag:0uqqzLlvdi47sDIebho0pQ==,type:str]
      value: ENC[AES256_GCM,data:eailrgE=,iv:ZvnLHnLqdl5ATZyKG2ftvEeWLJUgML5q6+Uv8xwW120=,tag:Btie/FBgNfiCWmkt3TYf8g==,type:str]
    - name: ENC[AES256_GCM,data:aaJx7yMxt0fjxwRVvX+NpJRLvHhipPXM,iv:yCXLtmBaYLXyuUwk6jLfPFVzIJzCDJOkhLSqb1q49qg=,tag:tuKbHYFoRQzqfysGFTviJg==,type:str]
      value: ENC[AES256_GCM,data:E8ibzOpVNuvuIhtj,iv:jicncTkPwD59AnN1IDydA4+CSSYOtAbOSjkSG/avDl4=,tag:Kog/tKdR+gHtFdW2XTfqHw==,type:str]
    - name: ENC[AES256_GCM,data:XL/U5ICV+jviBMtLyv1rJ9OKWg==,iv:j1QPdDYIaljHIIv1RA3emxtV+djm6o96jNOKETt/uGQ=,tag:1gccAEYYSEpqvRc8ihLuyA==,type:str]
      value: ENC[AES256_GCM,data:AFozkuVIsfXau1Zr6tPdXQh2RSe7tuEhp/ppbRlyHyYRFgtFfw==,iv:bQBFv3LJekq0lsSDsiy0zIKE509vtObz+utDezG9VE8=,tag:7zsgXNj9nPmkWZ26JPY1Bg==,type:str]
    - name: ENC[AES256_GCM,data:DUiETErSzyHsfIz9mcHIgCJm/A==,iv:K0vwcbKsOYnoemu1w4CdjwKGCjLWcc5Io8KjKYu66gw=,tag:0zeAu1t/Nq7z6WKZpOJpaw==,type:str]
      value: ENC[AES256_GCM,data:AoTi3/jHQa7QMzdidO4ExkX9Ceq4Al80cfCWHuvqn5soQUqNFTlpDBi5HZEoUyI7iwRuW1cDOj1o,iv:otY4Fxp6dTPkbXXm+SHBa1FYi1FassoGGHwDatJHOG4=,tag:91WZXZr9i3q8nt3trNHjZA==,type:str]
    - name: ENC[AES256_GCM,data:556zF04m89zM1h+vGhNW7xLdmQ==,iv:6CHNZBhe/D3QgGrP4/BCyR85LFcp4R0ijBtD1pitd2w=,tag:KmJORj7FB76XgFv8O9/n1w==,type:str]
      value: ENC[AES256_GCM,data:O+0tS/7UG6X0xHkVgaCbFY+r+lipHITdt0AaHYq+Svej,iv:V9Bf7Dt6c6qRmqPxxxzZYUZwm2bo0Wr9dkhsPpwZnH8=,tag:ZQZlQSkfMjXICoxwaY/9Ag==,type:str]
    - name: ENC[AES256_GCM,data:LrA5KMAcD+evAYl/1V/M0h99PZnR4JQ=,iv:UmIsdGG5YyC2tI7a993D6DUnU9scJpUO3eL+TWgjABY=,tag:Nq92vHYQGp6GdfMXxBr+cg==,type:str]
      value: ENC[AES256_GCM,data:5w==,iv:5em9FYvtvXWlDLwGE9eN1kgc8K9til4TXtcSHv2I6MY=,tag:yFX+JLMPGOY/9iXldEsPUg==,type:str]
    - name: ENC[AES256_GCM,data:6tl310j5PnfnFCH6JHrx9UglWFA=,iv:hXoqTdpFUffaqoLIHE0gbwK+LPa9RnEvwVI8FPPL9CI=,tag:vQbSzmvXkLQ83zm389W3Ag==,type:str]
      value: ENC[AES256_GCM,data:xQKxy/IfLtMMKSy7,iv:m4q/VneSvSQbNgxzqdCDriC/eZg48g/KkXOeIiuv3UI=,tag:UAJIrboe4qSZ7xnbm7gdVg==,type:str]
    - name: ENC[AES256_GCM,data:FjFdK3bAzOI=,iv:lPw9m1f9XpjC/D5rnmOsLcEuOqNLDs6KAYhQToQsqYY=,tag:J/e6kuVCzekDEVvNFCHxWg==,type:str]
      value: ENC[AES256_GCM,data:mi6ezDF/5tArhfLVkCAAHIbkEma9bt5jCK/I1+xh5ScyCN4YPyUHOJc=,iv:5SN2tP1YoFxfhUs/znnch/H+7u7fuMrTOow3GNsOJDI=,tag:ppzUNUs+RSZjOTuJsHtnWA==,type:str]
    - name: ENC[AES256_GCM,data:eIMAexHT9HI=,iv:VYxKSu3VKwR2DykecBgZ6ezIM4Dh3HnywWmteevSnY4=,tag:pg2UVY5D/8FcF3FBU9/ESA==,type:str]
      value: ENC[AES256_GCM,data:cYr/YA==,iv:GPKouutD7RA0p/BI5FPbMJRWZY9sdqMTwg2NMPKw9fM=,tag:p+B3aMCFyFYq0vwnJIL95g==,type:str]
    - name: ENC[AES256_GCM,data:ZncA5+3QJ111ZTcl,iv:o1gmPo43wNHG3pcbGH2wZWPQZFGFK3JVZ+pox7d8lrE=,tag:zn11+mnfa+p3jJ4dsfMcCw==,type:str]
      value: ENC[AES256_GCM,data:zwAtKiwj+DlBKtNw,iv:zKkGaxWd4RA9F1YA2RBVlreekqiCm8ctup2JiAdnCrU=,tag:uAMb1EvjlrPKyFOXipB0Pg==,type:str]
    - name: ENC[AES256_GCM,data:Z1poFvCgRWA7SN5H,iv:6/tbmy0ggJV57/eHBOrxGnD2k4YZVIjy0ov0G3utPqI=,tag:MRuYJxVYK9kxqBZmSxyn3w==,type:str]
      value: ENC[AES256_GCM,data:a9rzufyBE/+utqq0,iv:iWclUvry+yyepa1xe7uBGEwH3zl9QvLowuSoi35OiJc=,tag:P1VN6LTxXB271t4+nQs6gQ==,type:str]
    - name: ENC[AES256_GCM,data:3B0iTcCI/Dd+SKk=,iv:Wf2KbtpDuxY5EMBMm3qZa/Z5G5nCa/MKszdesXcvZuA=,tag:yAjDRM3hNMN2EQH814eE8g==,type:str]
      value: ENC[AES256_GCM,data:BBl6lZlj,iv:4+7vMHcEcTsZYmS/55FJP744Pjx07GmYoet0Vd4JghE=,tag:aXG2iR8kL7U9dsfaZBZ0sA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cmFWSGFQNVFtdGZOQ1d2
            cVVvTDJKUEJFOUlRbGFoSVczMHRHWFYwT1FZCnZHanRCU3MvN2NyMXdTMkVDM1Ba
            bWZFRkx4azJ3V25rZUFFdktCNjBzV1EKLS0tIFAyYzN6S3JWbnRtSllURTdsSUpl
            amNrVkk4R2diT2VlbVNCbVVjcE1WaGsKx2q5Gl5KBXH9qmVQ6YXIs4nOM02gH3xT
            NxKIkboToaLOiqTVVOaukTS4vAP6gU0yOsI4ijWZj1+4YG7QVGNn9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T20:23:05Z"
    mac: ENC[AES256_GCM,data:ZDY24eEmaTiPmvb/B77A8GFxGMa8LqoTOVvmI5h64BEXFNznBvZ6lz5NUZY0CtP/TWOP0YxICXTXFjr0gKJMICJ9oCwMoXRnmKYtsULXhqcBrYEihDg7OcEscSMMWLsjthaupLeaMJI+D61F/GSnLP6f2Bd7aqextNYj1+3lCQY=,iv:hT0ij7LWJ0p1IHoRg6uSTis7teszgdNK+IpK3t3Pn0k=,tag:E+EU1N9xfESF8Zj2s1Ke7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
