image:
    tag: ENC[AES256_GCM,data:Wrwu5EBd,iv:areTN3mISIfENdiHtr7Nwy2pyWaSA3G88RYCzqvfsdE=,tag:KTcaRzVb8gekBHNUoQDruA==,type:str]
    repository: ENC[AES256_GCM,data:WaaEAeb6ykXd/meqUC2TpiDxL+xj3l9XFtvIqe7w7iVv6yzodVHD,iv:WjV1Uki0MvUuiWSWRbDlMN1nWM4qHEDhnuJqatGzY18=,tag:VTHCI6VZiU0OCdbnucOghg==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:RPoZTw==,iv:AWFeup7E0AN31xQe/qjhaJldCeUv0lboZZ1hDqv4N0I=,tag:hBfEhqFOJKGLn9m8vNXbUQ==,type:bool]
    annotations:
        ingress.alb.yc.io/subnets: ENC[AES256_GCM,data:KwkS7R9H1bYTptU6wBByalIOYmY=,iv:O07gxwldTK35cqJOaordzm7Grne9v8ZRArQBLzT3fvw=,tag:Ed8aUTu8HpwTxPImPp78fA==,type:str]
        ingress.alb.yc.io/external-ipv4-address: ENC[AES256_GCM,data:s7HI5akHy1hju5Q5,iv:LKej/+WOVRA2/bl2DHndIdlVrHDtnZagU2GDVekrb8I=,tag:lZyBer02KuXwQwZZ1Zq0Qw==,type:str]
        ingress.alb.yc.io/group-name: ENC[AES256_GCM,data:f9wBGpYwqmqHWeLl,iv:sFawCXFjONO6uGf/aFXuTR21lop9R0boq8WjBLBFIlI=,tag:0Wboj9XwpoFfJApZyN4Kvg==,type:str]
        ingress.alb.yc.io/security-groups: ENC[AES256_GCM,data:x5YIpwftQEkcHhkS0btCSyYHJzA=,iv:/zW6Gn653+9BsVfb9RKNJ2Ste6FrfFUaZO167A3zwqA=,tag:v2wv074cGl50oItWnT0ajQ==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:zyjagCC/33q9Xi1f9sA/e4O1g32Ujg3sTtbZI0w=,iv:KGtX0flxn0zKBlspco7qiUYWNfJO4fuqTW57OWCcMv8=,tag:3/4vN/v/IMkX5GFk3c055A==,type:str]
          paths:
            - ENC[AES256_GCM,data:gE1q5K1YzMoZD9z209FN6RrdXr+XoZtZpJHzGwI4,iv:3siaTXlBDGaZr4XLRXirnLaMIE98WXhEbi2JavNXo9Y=,tag:OxHOkLoOOsT1YnGhYFZhKQ==,type:comment]
            - path: ENC[AES256_GCM,data:R9ezUg==,iv:5zO5ai9dDmLs0ltQReXQWtxDyUpGZF31UWrNbyb8sug=,tag:w7IaI/aYQqcKQRYljcV79Q==,type:str]
              pathType: ENC[AES256_GCM,data:Xxijze9a7SoeiRLBQfZxH0WtaIBt5g==,iv:WjK/uvRCZHUYMlzZzAu1x564XY2QkUkCq1VPNiiCj7o=,tag:5CIl0yJlbd+klHN1WoPn9w==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:RBd+tYIUTXF4GkmIlnjL66gHRktJnqURFx+8nIo=,iv:ILI7VQ8ww/urTw58VKjMshmwtwhZ3vYS5D5txW40vyg=,tag:mlggzW/6uboCuSeyDEiotw==,type:str]
          secretName: ENC[AES256_GCM,data:s1J7kyzpSDfYKz+5p/C/JoyUgRYrtlYBSwLkGzrn0eJyhqxa1VM+,iv:sFoSI0IFt7hgVRhVOswu6UK2CXRkksBqsNQPPclOjpI=,tag:7vSeBOLo5NxIaQ3lp+mDqg==,type:str]
service:
    type: ENC[AES256_GCM,data:EuNBgny1ZbY=,iv:ek30mUjyRFFQUOTciA6s89xZo/w9YaWNQgUcxSLdtY8=,tag:LBRALPuuVe3eNeATRrZytg==,type:str]
    nodePort: ENC[AES256_GCM,data:gCaAJPM=,iv:YQknICskkXcGPsIymDzIU7AUV7lV5ncOeIGiWv3xhXQ=,tag:PuuKcNbKdwnD3etDWsedNQ==,type:int]
env:
    - name: ENC[AES256_GCM,data:p6a6tr6OE4c=,iv:FuEx44PnZTmejj5kKmHN0xtuuKSBCXxm+DqHN2/Mh4A=,tag:0UaceE8/TdsZTaaifeS98A==,type:str]
      value: ENC[AES256_GCM,data:HWPOUmAvziQ=,iv:g5i/tksIAb1x8OQbyCkmX0uUcj8m7odFl5pSBV+0vFI=,tag:yO/f2vZidvi/UPojdYbRAg==,type:str]
    - name: ENC[AES256_GCM,data:rBYft8TUMzn7FaI=,iv:H1xeGsaeMMvJ2EzbESRGl4pAeVbsNQJxjAjMuEztD/c=,tag:E6BhxUySOsgVEPmddi3w8Q==,type:str]
      value: ENC[AES256_GCM,data:G3ivLpO8,iv:N5FcFzvEpdMqgaMVoUL1Kog2GwMjf3+rhk6EknCeMIM=,tag:93DpCVqCilAoG7CFVdnSYA==,type:str]
    - name: ENC[AES256_GCM,data:OnF9HRoFhRH5zDkFFJa8,iv:3geA7VbxRGCYEko5Kvj76mkbMdAYtSldBTyplgi2SnM=,tag:cK3HYeGZwEysjEcDqp61Bw==,type:str]
      value: ENC[AES256_GCM,data:n5osQicLtGN28Z++8NNv6i3jlekYlja38HqQFoNGXWhT3G2lTIUamGCRR5Dp,iv:lcWx9feUt42WMWjM4D4HwdchdNAbS6CU2aMozRvjc44=,tag:ReUzBaE4b0wf2JtetjP+Zg==,type:str]
    - name: ENC[AES256_GCM,data:5dL8GMYa59Jj7Nn0ILO4,iv:QQ4coLaWAiiqSfL/9wdv/He9iocGJS1YV/CQMDRsp9Y=,tag:pcPc7KtLWk052gSlM1B2WA==,type:str]
      value: ENC[AES256_GCM,data:8tUHdQ==,iv:19B1LpRrJjXmW39DPt+Wvp+VG5NTzKq1xkBGyQulGYY=,tag:ldwLWBsYKgVyzlVhsMQd3A==,type:str]
    - name: ENC[AES256_GCM,data:G/RX/khGsJctEJVwbQ==,iv:QTl4aBWKWxQAtOvE1vg9KzlO9fToHGL/q9JlXid9Cyw=,tag:uIX/AMjo4uRBwX2pLgfW6w==,type:str]
      value: ENC[AES256_GCM,data:gQ==,iv:wa1uz6CHk5hB0HPthNwPBR81ZLRRrUEv2ssNYsa3rnA=,tag:vJZKFYX5gkR8xSU4xf196w==,type:str]
    - name: ENC[AES256_GCM,data:LqrhHENmwyZd7kTMo86NOl0N1g==,iv:Fyx6vbINeZFdr/b8HggaeMLjHL9UBcM60NFNFO1fKQw=,tag:gQF9ZQgOCbs1+hLn8IoFeg==,type:str]
      value: ENC[AES256_GCM,data:mzBP7tOBvC77VfyTlSAK,iv:uYSeIB3VQdQx6KXTNrtm/NZ/Mx4ct8THzH+hNjq3oMI=,tag:h0b+lmYiirKX+MGX77PcZQ==,type:str]
    - name: ENC[AES256_GCM,data:VTDzDGdoflG5C2pugkk=,iv:STFhT4EQrEMN12vDCpSDNCth5U1JDfhOkwls8Hl1KJw=,tag:NjUaPMeKsmBEI0wu35B9bA==,type:str]
      value: ENC[AES256_GCM,data:kA==,iv:ovheZuajwdzuxpfuk/pKH+p4NSMZn/hl9CxVFVczKEQ=,tag:kACqFi3XduRqwN1SMSAnjw==,type:str]
    - name: ENC[AES256_GCM,data:ZxWyQKveN8ND+fDvy051ii5xapc=,iv:gLhkD4lpz3h0/66keHYN4R9EUcJXrsgzL4eWZsE0xBY=,tag:wm/LnADY/lV960vNdBTV/w==,type:str]
      value: ENC[AES256_GCM,data:y80iTgtFTL3byLfHqt9vMFONL/bBgydZkdltpLs2Ag==,iv:qlaapEfDH/stgQwvIzzN15SJabHJ4GCItLp39XkKIcg=,tag:nOOiq1UPLPIQ/Pzy8zcxNw==,type:str]
    - name: ENC[AES256_GCM,data:S+zLUSdUcKf6LJFWQNbbbA==,iv:rhz07A//zPkUQTOKPaFVvq960Df0zWcdAwB9gtkkzpc=,tag:zrV7Tc0z3SNead6wX7911g==,type:str]
      value: ENC[AES256_GCM,data:RWZrYB7N6E5NsbeZAoun1//hOUPLKvwCtpK7fEiPPVIps85e5dg8XPkO5LTA,iv:ST6jx5gqFwfQRm0dP7uvlXSazBC/r7mWSLbwZ0N7yAk=,tag:W82eP8UqUWHZtd7ztR9q7w==,type:str]
    - name: ENC[AES256_GCM,data:DzPj2v2JxQVGBDw4Uv6GrA==,iv:OVpEcVaUVZNdN8F5YKKveyukQ+9A1gUaRHNcr2eUq+U=,tag:pM09PoRkSZkK21oAHfNDVQ==,type:str]
      value: ENC[AES256_GCM,data:KjDKmA==,iv:b7uoSydaHe17ys7Xrw5sy65olqgT1LCs9eER7ccL42U=,tag:UBDPAiaHJCxB8junSgHT/A==,type:str]
    - name: ENC[AES256_GCM,data:tzvdnbpeiACFxlELeR0=,iv:QE2qcenaQaLblpUIqWgQYmGCYQ3cJ5/ouDsrt629qmc=,tag:KDKyIQvDiqJ5PKce2YgvAQ==,type:str]
      value: ENC[AES256_GCM,data:tA==,iv:hB2ZOdKRPJS4f86WhV1+yJDq0MgVK2oQjoEYj4UwPWc=,tag:dv6ipdYyKLOJuCGqpABqKg==,type:str]
    - name: ENC[AES256_GCM,data:AFbfS9tz5Sr8cFM+TKgA+zC+DWw=,iv:NWO5IQsWpJCNYYQlygPDT+GCVbgyQxEVBJnqFjolDi4=,tag:PudetnbCjBa3+IfDHKS64w==,type:str]
      value: ENC[AES256_GCM,data:JUb6zqQuaBbDh8lQF4ar,iv:ZbKedsmw6vqDwNHYDJ7TIAEMVCnoeABUg8NN9PzvPds=,tag:QjM7FyDPaeFpmOZD4prFgw==,type:str]
    - name: ENC[AES256_GCM,data:IKFt+4+gdoJMUIO6u3hT,iv:BnLoyDZDDTdl38ZAWAxF2drBpM7rNYoqrEtxrr6rrAI=,tag:eLa3EP2g0bNQHkQqpwIRIA==,type:str]
      value: ENC[AES256_GCM,data:Bg==,iv:2O647flczfr5J5zMwATx1HFcil+OH/5Wxk5rXmSCQZk=,tag:CNojkSl37jgmcKr1AhdPow==,type:str]
    - name: ENC[AES256_GCM,data:FCySgNwcan0Hek3GWOYNdlatnmfR,iv:WWneVeCfBw6H78/2TLH5vZvCJ8vI9MEfNNnRAgOpEaA=,tag:rAftlL30+yKVfiNCn3CUGA==,type:str]
      value: ENC[AES256_GCM,data:JZRzIrs3aYRhkLhmzRwLHszWj7wUObNvjaH4kREv5g==,iv:oIMZiPfGrljextnbdH7cUxXLtpuF6H7QTuOTqcKHGaM=,tag:z0itZ1CM9lX7PIJzHgtzkA==,type:str]
    - name: ENC[AES256_GCM,data:+yxUvScv/vM=,iv:M6ZmJsKHODi0zySsKvbhawpRG3fpwTab9jMBHrzU8nE=,tag:t57EMrW2bQefkUkhK5Vo/A==,type:str]
      value: ENC[AES256_GCM,data:2bmBqE+pT/Mzmhz0rX59mCBeoZRs22acElyI0u9K6Q==,iv:nKwX5F9LgeMohczxAVC0FTtnf0Uvv2kjo9JVPZQYNFg=,tag:iRbfmI5g3dWblo/Ue/mFZA==,type:str]
    - name: ENC[AES256_GCM,data:3oB0bm1yyUmyAQ==,iv:jB1abPWslNy6POy5Dgynu9t7Gr3ADDv5yDxDuzEvW/g=,tag:4uVTqbWcidlF9yesHBPBcg==,type:str]
      value: ENC[AES256_GCM,data:3FCGGcPQ4w==,iv:y3qMSw8x+0zTTZVwuOS3re6BUGt5wku0/viy1eoXNlA=,tag:bnBT06Buk5yopz6GKhmQcA==,type:str]
    - name: ENC[AES256_GCM,data:I5mHw5QnjDgpGYjvGR4rRWw=,iv:XMRjbKx2nYpm3kicbi+TPp//a6OcOS1oamT+phmBGbo=,tag:42vNbVo1hULQ6Z2OHgSbpQ==,type:str]
      value: ENC[AES256_GCM,data:0gf2TRiBR4luTMLJ3Dek+j1ahKu7TWYygA==,iv:sNRIlxJQ5ueJvGjKKspTvCsIG5+B5OFrtExH94NRLtk=,tag:tDi6a1B7jPIFgR61RWUsVw==,type:str]
    - name: ENC[AES256_GCM,data:jAUj4Fyv5BPpKdIvrrw=,iv:1OiH96nEF4z7FEMSeTw59+QljQ0b8+Fkn3T4ktw2u8o=,tag:4VOjz0dIFhPgj/KBDLUslw==,type:str]
      value: ENC[AES256_GCM,data:MQaUEENUnFfm46EM+Rlk+2leXqnqOkYOw6faw5+ArHCF6q7hx4wHzA==,iv:XoCMWIr65LjCDYh1+rLBBsQejlQu3NwP1dXxOF8zeCA=,tag:R0I40EVi01FtDZtQ5tpYkw==,type:str]
    - name: ENC[AES256_GCM,data:1UX7/cOYys0llzExg7o=,iv:Krk7QBqMjh0x03uYuZpRSxgLriJML3VN3FI7r40Zhjs=,tag:Gqc1VHgUEK3Gz1zZevWqHw==,type:str]
      value: ENC[AES256_GCM,data:ZNtXpxMuWBmiBISOK0olBmtoZuwwnNPTF+sJr9D6opIS2TgM3w==,iv:li7sBS1OAxM0OxNl5v+ZdxG2VVO9vccc34XvthU5bC0=,tag:x4fBGfMCsOSar7EYRPY3KA==,type:str]
    - name: ENC[AES256_GCM,data:+0wsB3qkQb9Bdvwhq/Cp,iv:cDHZuHtdAat6NZVSbotx2s/mTFbGtd2dzCkSvfieBnk=,tag:HIRdrvwSsZacyRHTc5y1vA==,type:str]
      value: ENC[AES256_GCM,data:H8CJlw==,iv:01koMEEEdBpkWVfEJtiVrPmTuKmbySyQRDxuBkcWsB0=,tag:N8JtUOhS4vUVWNtX87YsvQ==,type:str]
    - name: ENC[AES256_GCM,data:2fqv0F9qKSGwezI4z7Jto0xLJw==,iv:bcwqU22L5MehJoANGNcHjMBwg7PK30V8nPueJZG5puI=,tag:ezzXVhAVmd3PIps8iH/gRg==,type:str]
      value: ENC[AES256_GCM,data:gfRUsASXyt5U8UDN,iv:HMf1QsJqxK90Fjc5WAismjnhiRMVDnQ6QRPnYsQ+9JQ=,tag:G66uOCXIzdmKlhXUS7ZAyQ==,type:str]
    - name: ENC[AES256_GCM,data:WJSe8ix7LTmfUJRo06uv06bp7PS1yjWH1wWA,iv:GsiAbwsyR0Pl39a9zCWR2bPYXVDPeT70nIwaoEOtee0=,tag:G6rKiqj3BjCX2jHTcrJx6g==,type:str]
      value: ENC[AES256_GCM,data:BXy9CdPDFTguJAtDCpk87rRASnvSX3A60ZXByMnT0aI=,iv:Juzv/BGlcqgiXuuvb+cpDwj10Kj3pg465DLz607yLYU=,tag:q1JnWHQlfno21k/dQZJxFg==,type:str]
    - name: ENC[AES256_GCM,data:ouWr0SLnn6HJF7VZwUM2y2neD5l2vFNnmUAN,iv://HdDbU9yq+aRPm7sw2q2mLxEQgkDv2NUP8zfiyBOS4=,tag:gqlUnybkd7SaNSJBHAMhUQ==,type:str]
      value: ""
    - name: ENC[AES256_GCM,data:qg0KR8lxWXvaFnwxVnSiTHA3CmfTQ66C,iv:O4KAViJXsZMcNkIt/yIM9D/9IMg1oNChb01tOiHkTq4=,tag:xmnDR26EwU2K78Ju8EeurQ==,type:str]
      value: ENC[AES256_GCM,data:75H7v+c=,iv:FyPn8R4biOXrQt4u590qJ9zav2bPLDsYF+j+ndvTcog=,tag:eiNL94eY3IW6usT+A+iSag==,type:str]
    - name: ENC[AES256_GCM,data:fnVUzGXG0VSer5qHWxwz17MZelCNsGNQ,iv:50SJ51TN5TuLyc/g/oStBnixrfJzjijwSSJXGVPZ2HA=,tag:K3bRwloYqjmbJmJOrFS+nw==,type:str]
      value: ENC[AES256_GCM,data:09NOq/TnzHZkVB0+,iv:kIXjxW9cu+8RxdbFe1j23ZPVnND0RWZxOAzjy+juZ9I=,tag:J+PJlGykrLT+DuzzB/HiuA==,type:str]
    - name: ENC[AES256_GCM,data:m4/s9yqnlK/hv8blmdfkudQHeA==,iv:8NiKsMHLMXbKZ/sHe6Vn/zU6K0lKfKrO1aGohwVDJQg=,tag:EsITWCzW+5KJk6b7IgIsEA==,type:str]
      value: ENC[AES256_GCM,data:a6uWoHtC1GePT2nin1axfNDA8fIBKRnN25qW35PPkYiVc8WSvw==,iv:lgnOPzjVq6wCBfAPKrV4hj/JNFKuXH0gZp8bkEkDDFA=,tag:+mQfizP6qe0neMjML+O5sQ==,type:str]
    - name: ENC[AES256_GCM,data:bl6yKTzeCMPJNCxpbXLyMoDiFA==,iv:0eRu98JjHHH3Ld+xtBjVi1rFqvJEC+ZNCDgP7gxn7HU=,tag:AcQNDzC7Eka3EN7xBlx89Q==,type:str]
      value: ENC[AES256_GCM,data:L+M7zlRUSSETerJg+zaRB6Np700keTPRuZWF+KP/vXTyGTzhY7vnnpBjcK8kOfYg3KWeCsAgwIMX,iv:ONCk8rArFwxT6Wy4WoxNcFGqcsBxDbaQ9JYf4MQ6L74=,tag:HC/JFWd+/PC63l3PYPZycg==,type:str]
    - name: ENC[AES256_GCM,data:9eEs0lBb6SOTzCGRXGAiAdXL/w==,iv:bsg3ZpjbqvNyGyMzKRLxtOLbCyjaNppLq1yWkiJBsFY=,tag:K21JdFPrMQW6xpkD4cOTCQ==,type:str]
      value: ENC[AES256_GCM,data:aSL/ehkURgfQvIK7zP2y1XHy1aliLPT1/58oOjkVrKo5,iv:o8izLVsY8hjWH20J/zND+t6x6wPadPDJIKJ+cYetC9c=,tag:flNDis/ueTS/HM6PnYCRyw==,type:str]
    - name: ENC[AES256_GCM,data:CXDKfppfpORRzzS80AO1pZsxqP7kqXQ=,iv:RVVtw5HeQVseA6/QhS+8212PNzwVRB57DjQ+eKF0GvA=,tag:2Dbp5CaSd6nl0Z4huecC9A==,type:str]
      value: ENC[AES256_GCM,data:cw==,iv:eQHYV0nUnR89QuU47qrUWCxp6OLrSl/ohTIcgM4sbNU=,tag:r1gJFShZhCs6KK06WqakVQ==,type:str]
    - name: ENC[AES256_GCM,data:rDZO44Rie6y9/xPQKyI4g4F7jo8=,iv:ZpPhKkAAc4EnGUkO33h5jhCgHVO+1vLBQ6cf5ZLu7eQ=,tag:6k0XwF9c/0a/j2et9vZijg==,type:str]
      value: ENC[AES256_GCM,data:rvfhEZxFjYZkzBAm,iv:mEEiV87PfszbMs347VReWp63MtJeZdVN25IisJRNHWk=,tag:AwsITDx/ZFK+TpXxf/32AQ==,type:str]
    - name: ENC[AES256_GCM,data:2O7Zo9XUrLw=,iv:7fQVIGPBE2OW1eM+1JIT0ARnTeimi1tXi3Rjiv/gpbM=,tag:s2Z4+jW+yItSK5dZ7VId/Q==,type:str]
      value: ENC[AES256_GCM,data:Owqbu3PA+0S3R+nX0EekfcoLHq52S2npN6epHUL46lejgQ4hhoxQ15o=,iv:bgSYlX+KIBkmms2VqGrDm/P7UklY7FAMk77So7SFZgE=,tag:FrF0fX7Sh0tzAjTdm2TUPw==,type:str]
    - name: ENC[AES256_GCM,data:adgIFHwzgas=,iv:yr4tPhQL4Q7kySPeQI++wtpEnxyBm8OgqYFgrB4nWBM=,tag:OthPSNxu4XDfQyepry/x1A==,type:str]
      value: ENC[AES256_GCM,data:BKWNvw==,iv:fbiw9jMAukbBWHXB0UPGBzMkD2QdG/k0RjH9skX3xhA=,tag:Z2cTdGLUwinraBQtYZjs7w==,type:str]
    - name: ENC[AES256_GCM,data:yU1uUyq7Lqwj0p5t,iv:5wJEiNMGzbHndKR4Nueh2iKIebZlXCqObn82fx4mHNY=,tag:hU9dBMxO5ejkJymrr0Wlsg==,type:str]
      value: ENC[AES256_GCM,data:hH5Jcw8mxMaJapLd,iv:HYvtp3q/+6pN+XEiU7JxtwW2oSbO9EriOocl5wpMY4g=,tag:4R4G/CPFdsY/x69aD7FXiw==,type:str]
    - name: ENC[AES256_GCM,data:tsYzzET9phaDZDdD,iv:6+JTLxiSoaDf2HqnROlGMhm6ruDSJeyk5JKnBe2ZVhA=,tag:Tfrx4GpQhQdQ35NtdNEGAw==,type:str]
      value: ENC[AES256_GCM,data:kyIsbNSi9Q9QythV,iv:ZO2YqhTzJHLsBPk9nnXRkNuDrnn/HJ1XXzXW0NkQx0k=,tag:7Umv7dhOTCBJcIZMhWRw7w==,type:str]
    - name: ENC[AES256_GCM,data:KXxbX5T7If8kf4M=,iv:spd0njn04+duP8xGWbBwYup6/jL1bxknftjlR8SkV3Q=,tag:OZevGq5SCArkRyecmXEjIQ==,type:str]
      value: ENC[AES256_GCM,data:myCfxLw7,iv:KOhzQ73/kMaVIc59Wn39cMNWWAIlAMFIywpRCihwsFY=,tag:DcY0k2EE9/Q/mfRkH3z9TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pj5elnqgt6c4yaatfpv652c8kcn4pwty2ez5l8y7e0rwh9e0gcpqkjj4xn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITUNmVjhMdnZNR3luSVho
            L3N0N3hQOTFYTkptWU1nVkd1N3dFUzNQUTNjCnJmeklCUGdyOVdEVDFEUDJzUENp
            OFdhLzNyTXAzTVIzVGJpUlBoaFRGVGsKLS0tIGc5aFU0ZTV0bVR1NlpPMWlHdDhr
            L0hFdW9mWVVuaGk1WmJYNEtuV29samsKMZQr5EL0OL9+UnmOjMlhe594VpSVnBb4
            Lj4L0fuk/eOeJClDYyT/swzvb8mwPZVMjZX0AFxnxObGoMIxkHWzJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T13:50:05Z"
    mac: ENC[AES256_GCM,data:Ow+LcsdtyXfuZsLqnaN/SVLJ2OXO35iiZJQZvMrB5iPpPzGO1w61sX8WhyTaL61kilhHT53TJQmJjvobM3rhxm6ZBGiQ2F1X8DNlAiljPLFxmKBt/B+cyAWkBAc9Mog8sDYsQ8azh3nVylwIV6PUTyctEwjlyP8X0syEx40ZiXo=,iv:kff6N4P+BBlima9gblsO/krBbsgqs6Uq71I2NrU1lvg=,tag:ddH4tD66QYJ7noPhkE4UXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
