replicaCount: 0

image:
  repository:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "FIXME"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   requests:
     memory: 12Gi
#     cpu: 100m
  # limits:
  #   memory: 128Mi
  #   cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}

#migrations:
#  activeDeadlineSeconds: 300
#  # command:
#  #   - sh
#  #   - -c
#  #   - "echo hi"
#  command:
#    - sh
#    - -c
#    - "python manage.py collectstatic --noinput && python manage.py migrate"
#  podAnnotations: {}
#
#  podSecurityContext: {}
#    # fsGroup: 2000
#
#  securityContext: {}
#    # capabilities:
#    #   drop:
#    #   - ALL
#    # readOnlyRootFilesystem: true
#    # runAsNonRoot: true
#    # runAsUser: 1000
#
#  resources: {}
#    # limits:
#    #   cpu: 100m
#    #   memory: 128Mi
#    # requests:
#    #   cpu: 100m
#    #   memory: 128Mi
#
#  nodeSelector: {}
#
#  tolerations: []
#
#  affinity: {}

env:
  - name: APP_NAME
    value: logo-api
  - name: APP_VERSION
    value: 0.0.0

  - name: REDIS_ARQ__HOST
    value: localhost
  - name: REDIS_ARQ__PORT
    value: 6379
  - name: REDIS_ARQ__DB
    value: 1
  - name: REDIS_ARQ__PASSWORD
    value: ""
  - name: REDIS_ARQ__SSL
    value: 0
  - name: REDIS_ARQ__CERT_PATH
    value: /certs/YandexInternalRootCA.crt

  - name: REDIS_MISC__HOST
    value: localhost
  - name: REDIS_MISC__PORT
    value: 6379
  - name: REDIS_MISC__DB
    value: 2
  - name: REDIS_MISC__PASSWORD
    value: ""
  - name: REDIS_MISC__SSL
    value: 0
  - name: REDIS_MISC__CERT_PATH
    value: /certs/YandexInternalRootCA.crt

  - name: SD__MOCK
    value: 0
  - name: SD__USE_DIFFUSERS
    value: 1
  - name: SD__BASE_MODEL_PATH
    value: 'stabilityai/stable-diffusion-2'
  - name: SD__REPO
    value: ''
  - name: SD__HF_TOKEN
    value: ''
  - name: SD__OUTDIR
    value: /outputs
  - name: SD__SKIP_GRID
    value: 1
  - name: SD__SKIP_SAVE
    value: 0
  - name: SD__DDIM_STEPS
    value: 10
  - name: SD__PLMS
    value: 1
  - name: SD__LAION400M
    value: 0
  - name: SD__FIXED_CODE
    value: 0
  - name: SD__DDIM_ETA
    value: 0.0
  - name: SD__N_ITER
    value: 1
  - name: SD__H
    value: 128
  - name: SD__W
    value: 128
  - name: SD__C
    value: 4
  - name: SD__F
    value: 8
  - name: SD__N_SAMPLES
    value: 1
  - name: SD__N_ROWS
    value: 0
  - name: SD__SCALE
    value: 7.5
  - name: SD__FROM_FILE
    value: 0
  - name: SD__CONFIG
    value: /configs/stable-diffusion_v1-inference.yaml
  - name: SD__CKPT
    value: /models/model.ckpt
  - name: SD__SEED
    value: 42
  - name: SD__PRECISION
    value: full

  - name: S3__HOST
    value: https://storage.yandexcloud.net
  - name: S3__BUCKET
    value: s3-logo
  - name: S3__ACCESS_KEY_ID
    value: no_id
  - name: S3__SECRET_KEY
    value: no_secret
