replicaCount: 1

image:
  repository:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "FIXME"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

#migrations:
#  activeDeadlineSeconds: 300
#  # command:
#  #   - sh
#  #   - -c
#  #   - "echo hi"
#  command:
#    - sh
#    - -c
#    - "python manage.py collectstatic --noinput && python manage.py migrate"
#  podAnnotations: {}
#
#  podSecurityContext: {}
#    # fsGroup: 2000
#
#  securityContext: {}
#    # capabilities:
#    #   drop:
#    #   - ALL
#    # readOnlyRootFilesystem: true
#    # runAsNonRoot: true
#    # runAsUser: 1000
#
#  resources: {}
#    # limits:
#    #   cpu: 100m
#    #   memory: 128Mi
#    # requests:
#    #   cpu: 100m
#    #   memory: 128Mi
#
#  nodeSelector: {}
#
#  tolerations: []
#
#  affinity: {}

env:
  - name: APP_NAME
    value: logo-api
  - name: APP_VERSION
    value: 0.0.0

  - name: REDIS_ARQ__HOST
    value: localhost
  - name: REDIS_ARQ__PORT
    value: 6379
  - name: REDIS_ARQ__DB
    value: 1
  - name: REDIS_ARQ__PASSWORD
    value: ""
  - name: REDIS_ARQ__SSL
    value: 0
  - name: REDIS_ARQ__CERT_PATH
    value: /certs/YandexInternalRootCA.crt

  - name: REDIS_MISC__HOST
    value: localhost
  - name: REDIS_MISC__PORT
    value: 6379
  - name: REDIS_MISC__DB
    value: 2
  - name: REDIS_MISC__PASSWORD
    value: ""
  - name: REDIS_MISC__SSL
    value: 0
  - name: REDIS_MISC__CERT_PATH
    value: /certs/YandexInternalRootCA.crt

  - name: S3__HOST
    value: https://storage.yandexcloud.net
  - name: S3__BUCKET
    value: s3-logo
  - name: S3__ACCESS_KEY_ID
    value: no_id
  - name: S3__SECRET_KEY
    value: no_secret

  - name: KEYCLOAK__HOST
    value: "https://auth.example.com"
  - name: KEYCLOAK__REALM
    value: "logo"
  - name: KEYCLOAK__CLIENT_ID
    value: "logo-backend"
  - name: KEYCLOAK__CLIENT_SECRET_KEY
    value: ""
  - name: KEYCLOAK__CLIENT_PUBLIC_KEY
    value: ""
  - name: KEYCLOAK__ADMIN_USERNAME
    value: ""
  - name: KEYCLOAK__ADMIN_PASSWORD
    value: ""

  - name: CORS__ALLOW_ORIGINS
    value: "*"
  - name: CORS__ALLOW_HEADERS
    value: "Origin,X-Requested-With,Content-Type,Accept,Authorization"
  - name: CORS__ALLOW_METHODS
    value: "GET,PATCH,PUT,POST,DELETE,OPTIONS"
  - name: CORS__ALLOW_CREDENTIALS
    value: 1
  - name: CORS__EXPOSED_ROUTES
    value: "/api/v1/ping"

  - name: PG__HOST
    value: "localhost"
  - name: PG__PORT
    value: 5432
  - name: PG__USERNAME
    value: "user1"
  - name: PG__PASSWORD
    value: ""
  - name: PG__DB_NAME
    value: ""

  - name: TRANSLATE__MOCK
    value: 1
  - name: TRANSLATE__API_KEY
    value: 'dummy'
