apiVersion: v1
kind: Service
metadata:
  name: {{ include "logo_ui.fullname" . }}
  labels:
    {{- include "logo_ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "logo_ui.selectorLabels" . | nindent 4 }}
